### ISSUE TITLE
quaternion.rotate_vectors is way slower than expected

### ISSUE THREAD

**Issue by erniejunior** [moble/quaternion#101]
Although the docstring mentions that other methods could be faster, I did not expect `quaternion.rotate_vectors` to be almost a 50 times slower compared to the naive python implementation. This one might be related to or fixed by #3.

**To Reproduce**
```python
In [1]: import numpy as np

In [2]: import quaternion

In [3]: def rotate_vector(q, v):
   ...:     return (q.conjugate() * np.quaternion(0, v[0], v[1], v[2]) * q).components[1:4]
   ...: 

In [4]: v = np.random.uniform(-1, 1, 3)

In [5]: %timeit rotate_vector(quaternion.z, v)
1.08 µs ± 43.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [6]: %timeit quaternion.rotate_vectors(quaternion.z, v)
45.3 µs ± 112 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

**Expected behavior:**
I expected the `quaternion.rotate_vectors` function to be at least on par with the unoptimized naive python implementation.

**Environment:**
 - Linux Mint with 4.8.0-53-generic kernel
 - Installation method pip
 - Numpy version: 1.16.0
 - Quaternion version:  2019.2.5.11.11.26

**Additional context:**
numba is installed

**Comment by moble** [comment]
The difference you're seeing is entirely due to overhead.  You tested on just one vector; if you operate on many more vectors, you'll see the timings reverse.  The "naive" version you provide does absolutely no checking of input arguments, and doesn't generalize to allow for arbitrary input dimensions or chosen axes on which to operate.  If you look at the [the code for `quaternion.rotate_vectors`](https://github.com/moble/quaternion/blob/2c782e4ed8146961264685077eec31c9a4d826a5/__init__.py#L598-L611) you see that it does a lot of massaging so that it can take arguments of all types (lists, arrays, tuples, etc.) and shapes and sizes, and raise an exception if something is wrong.  The quaternions don't even have to be normalized!

If I drop these requirements, the simplest I can reasonably make a function that uses this algorithm would be
```python
def rotate_vectors_less_overhead(q, v):
    """Same as quaternion.rotate_vectors, without all the axis fanciness and checking"""
    m = np.array([
        [1.0 - 2*(q.y**2 + q.z**2), 2*(q.x*q.y - q.z*q.w), 2*(q.x*q.z + q.y*q.w)],
        [2*(q.x*q.y + q.z*q.w), 1.0 - 2*(q.x**2 + q.z**2), 2*(q.y*q.z - q.x*q.w)],
        [2*(q.x*q.z - q.y*q.w), 2*(q.y*q.z + q.x*q.w), 1.0 - 2*(q.x**2 + q.y**2)]])
    return np.einsum('ij,...j', m, v)
```
Of course, `einsum` still has plenty of overhead, and this version isn't nearly as flexible or robust as the `quaternion` version.

So now we can compare these timings for a single vector:
```python
>>> v = np.random.uniform(-1, 1, 3)
>>> %timeit rotate_vector(quaternion.z, v)
1.97 µs ± 86.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
>>> %timeit rotate_vectors_less_overhead(quaternion.z, v)
6.99 µs ± 27.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
>>> %timeit quaternion.rotate_vectors(quaternion.z, v)
70.1 µs ± 584 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
As you can see the "less-overhead" version is ~10 times faster than the `quaternion` version, but still ~3.5 slower than your "naive" version.  But only when looking at a single vector.  Let's see how we do on, say, a million vectors — and maybe with some more interesting shapes, though still something the "less-overhead" version can handle.  I won't bother testing a generalized version of your code because you might quibble about how it could be optimized, but it's probably fair to say that any similar code would take around 2 seconds with so many vectors.
```python
>>> v = np.random.rand(10, 25, 4, 1000, 3)
>>> %timeit rotate_vectors_less_overhead(quaternion.z, v)
27.3 ms ± 424 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
>>> %timeit quaternion.rotate_vectors(quaternion.z, v)
27.6 ms ± 209 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
These are about 100 times faster than your "naive" code would be with this many vectors.  It also suggests that the `quaternion` version runs at about 27 ns per vector, which means that the 70 µs I got above were essentially completely overhead.

So the summary is that this function trades about 70 µs of overhead per call for far greater robustness, the ability to generalize, and very fast operation per vector.  If that overhead is actually a problem, you should probably look into reorganizing your code so that it's not a problem, or coding this functionality for yourself.  Also, as the docstring suggests, there are different possible algorithms for rotating a vector; the optimal choice depends on your exact needs.

---

I also want to point out that you rotated the vector `v`according to

    q.conjugate() * v * q

This is opposite to how I do things:

    q * v * q.conjugate()

The difference is just a convention, and it doesn't affect the basic functionality of the core code, but things like `rotate_vectors` are built using my convention.  As always, I recommend writing some simple tests for yourself to ensure that any code you write or use actually does what you expect.

**Comment by moble** [comment]
> each vector rotation depends on the previous one

That comment plus the fact that you're worrying about a tiny overhead on each call (suggesting that you have to make many calls) makes me wonder if there's an underlying ODE controlling your problem.  In such cases, I frequently find that the system can be turned into an ODE for the quaternion alone, which would allow you to avoid the rotation.  And if you're integrating an ODE, be sure that you're using an efficient integrator, because that will swamp any tiny optimization you do elsewhere.

But, if that's really not the case, I'd say your best bet would be to implement the rotation very explicitly (don't bother using `quaternion` objects), with as many assumptions as you want (so no argument checking or treatment of different shapes), and no allocations within the code (construct your "quaternion", input vector, and output vector once before your loop begins, and then just reuse them at each step by re-assigning the values).  That is, I would guess that something like this is what you need (but check the core formula, because I haven't)
```python
from numba import njit

@njit
def rotate_vector(q, v, vprime):
    vprime[0] = + q[0]*v[0]*q[0]+ q[0]*v[2]*-q[2]+ q[1]*v[0]*-q[1]+ q[1]*v[1]*-q[2]+ q[1]*v[2]*-q[3]+ q[2]*v[1]*-q[1]+ q[2]*v[2]*q[0]+ q[3]*v[2]*-q[1] - (+ q[0]*v[1]*-q[3]+ q[2]*v[0]*-q[2]+ q[3]*v[0]*-q[3]+ q[3]*v[1]*q[0])
    vprime[1] = + q[0]*v[0]*-q[3]+ q[0]*v[1]*q[0]+ q[1]*v[0]*-q[2]+ q[2]*v[0]*-q[1]+ q[2]*v[1]*-q[2]+ q[2]*v[2]*-q[3]+ q[3]*v[0]*q[0]+ q[3]*v[2]*-q[2] - (+ q[0]*v[2]*-q[1]+ q[1]*v[1]*-q[1]+ q[1]*v[2]*q[0]+ q[3]*v[1]*-q[3])
    vprime[2] = + q[0]*v[1]*-q[1]+ q[0]*v[2]*q[0]+ q[1]*v[0]*-q[3]+ q[1]*v[1]*q[0]+ q[2]*v[1]*-q[3]+ q[3]*v[0]*-q[1]+ q[3]*v[1]*-q[2]+ q[3]*v[2]*-q[3] - (+ q[0]*v[0]*-q[2]+ q[1]*v[2]*-q[1]+ q[2]*v[0]*q[0]+ q[2]*v[2]*-q[2])
    return
```
Timing this gives me
```python
>>> q = np.array([0, 0, 0, 1.0])  # note that the "quaternion" is just a numpy array of the components
>>> v = np.random.uniform(-1, 1, 3)
>>> vprime = np.empty_like(v)
>>> rotate_explicit_compiled(q, v, vprime)  # call once to compile before timing
>>> %timeit rotate_explicit_compiled(q, v, vprime)
800 ns ± 10 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```
This is about 2.5 times faster for me than your naive code was on my machine.

**Comment by mx781** [comment]
Hi @moble, I had this exact use-case as well and your explanation was super helpful in getting to the bottom of it, thanks! The direct calculation you have here (`rotate_explicit_compiled`) seems close, but not quite right - I had to transpose the matrix and flip the signs of the diagonals 1-off from the center, resulting in this:

```python
@njit
def rotate_vector_numba(q, v):
    vprime = np.empty_like(v)
    vprime[0] = (q[0]**2 + q[1]**2 - q[2]**2 - q[3]**2)*v[0] - 2*(q[0]*q[3] - q[1]*q[2])*v[1] + 2*(q[0]*q[2] + q[1]*q[3])*v[2]
    vprime[1] = 2*(q[0]*q[3] + q[1]*q[2])*v[0] + (q[0]**2 - q[1]**2 + q[2]**2 - q[3]**2)*v[1] - 2*(q[0]*q[1] - q[2]*q[3])*v[2]
    vprime[2] = 2*(q[1]*q[3] - q[0]*q[2])*v[0] + 2*(q[0]*q[1] + q[2]*q[3])*v[1] + (q[0]**2 - q[1]**2 - q[2]**2 + q[3]**2)*v[2]
    return vprime.T
```

What's the underlying formula you're using here, for reference? Is it effectively the same `v' = v + 2 * r x (s * v + r x v) / m`?

**Comment by moble** [comment]
Yeah, as noted above that function you should "check the core formula, because I haven't".  Also, I think I was attempting (but failed) to adjust signs to agree with the OP's `q.conjugate() * v * q` convention; yours does appear to be correct for the `q * v * q.conjugate()` convention, which is the underlying formula I generally use in this code.  (It can be preferable to use `q * v * q.inverse()` if the quaternions are built up in a way that may be susceptible to error.)  That other formula with cross products should be equivalent.
