### ISSUE TITLE
multiplication with real scalar seem slower than expected

### ISSUE THREAD

**Issue by 2sn** [moble/quaternion#102]
**Describe the bug**
Multiplication of a quaternion with a real scalar seems to take at least as long as multiplication with a quaternion; even longer when multiplied from the right.

**To Reproduce**

```python
import quaternion as quat
q = quat.quaternion(1,2,3,4)
timeit 3.*q
timeit q*q
timeit q*3.
```
(increasingly slower speed, the last one about 30% slower than the first)

**Expected behavior**
scalar multiplication should be a lot faster, and multiplying from left or right should make no difference.

**Environment (please complete the following information):**
 - OS, including version: Fedora 29
 - Installation method: pip, python 3.7.2 installed from source
 - Numpy version (use `np.version.version`) 1.16.1
 - Quaternion version (use `quaternion.__version__`)  2019.2.16.13.38.20

**Additional context**
interestingly, complex numbers of python also have an asymmetry in execution time, but in that case, the scalar as first operator is slowest, as one may understand since python will attempt the __mul__ function of the scalar first, then back up to use the __mul__ function of the complex number.

I also find the `np.conjugate(q)` rather slow, same time as multiplication.

**Comment by moble** [comment]
These numbers aren't surprising, but they're also a bit misleading.  Python is designed for convenience, rather than speed; numpy was designed to improve the speed of numerical operations, but it can only improve the speed *after* python passes operations to it.  This means that there's always an overhead — and not necessarily a symmetric overhead.  In particular, python objects are very complicated, usually taking up *far* more memory than is strictly necessary for a given operation.  That means every operation requires a lot more memory allocation than you'd expect, accessing complicated attributes via pointer dereferencing, etc.  In this case, each of the operations you're timing takes (on my laptop) 85 to 110 nanoseconds, which really isn't much, meaning that much of this will be overhead.

When looking at timings for numpy (or quaternion, in this case), if you want to get around the *python* overhead, you need to do many operations at once.  For example:
```python
import numpy as np
import quaternion
qs = quaternion.as_quat_array(np.random.rand(10000, 4))
%timeit 3.*qs
%timeit qs*qs
%timeit qs*3.
```
Here, the first and third are indistinguishable, and the second takes about twice as long.  In each case, these timings are 2 to 4 nanoseconds per element, suggesting that the timings above were something like 95% overhead.  Now, you might be wondering why `qs*qs` is *only* twice as slow as `3.*qs`, when there are far more than twice as many arithmetic operations being done for the former.  The reason is that, again, we've run into an overhead, though it is a different type in this case — presumably because the operations are so simple that the CPU is done with them much faster than the data can be passed to it from the RAM.

Anyway, you should take a step back and consider whether this is really a significant bottleneck.  If it is, you should either try to refactor your code to do many operations at once, or rewrite the loop over these operations in something faster than python — numba, cython, C, etc.  This might require rewriting the quaternion operations for yourself (though if you're getting really down to basics as far as C or cython, you could just reuse `quaternion.h` and `quaternion.c` from this module).
