### ISSUE TITLE
Does not rotate 3d numpy array . 

### ISSUE THREAD

**Issue by Nirajkandpal** [moble/quaternion#104]
Hi there, 
              I am trying to rotate a 3D numpy array using quaternion  as in   issue #39   . It seems to make changes in my numpy array but unfortunately this code below does not seem to rotate the 3d numpy array (it is an ellipsoid). I do not know if  I misunderstood or it is not possible to rotate using quaternion .
The code is as follows:

from astropy.io import fits
import numpy as np
import scipy
from scipy import ndimage
import skimage
from skimage import draw
import quaternion
import pandas as pd

im = '/home/kandpal/G327/sio'

data, hd = fits.getdata(im+'.fits', header=True)

mask = skimage.draw.ellipsoid(30,10,10)

x = 150
y = 75
z = 75

data_new = data[:,263:422,650:809]

dta = np.zeros_like(data_new)

arr3 = mask.reshape((23,483,3))

Data = []

angle1 = 90

rotation_x = np.exp([quaternion.quaternion(1, 0, 0) * angle1*(np.pi/180) / 2])

rotd = quaternion.rotate_vectors(rotation_x, arr3)
rotds = rotd.reshape(63,23,23)
dta[x:x+rotds.shape[0], y:y+rotds.shape[1], z:z+rotds.shape[2]] = rotds
data_new1 = dta +data_new
flux = np.sum(data_new1)
Data.append([round(angle1*180/np.pi,2), round(flux,2)])

df = pd.DataFrame(columns = ['angle1','Flux(Jansky)'], data = Data)
print (df)

fits.writeto('/home/kandpal/Desktop/overlap.fits', data_new1,hd, overwrite = True)

**Comment by moble** [comment]
This is a bad *minimal* working example, because it involves a lot of things other than the quaternion part of your code.  Plus, I can't even run it because I don't have your data — so it's technically not even a *working* example.  All that means that I don't really understand your code.  Next time you ask someone for help with code, you're more likely to get help if you can write a simpler example.  Nonetheless, I can see that you've made a lot of mistakes, even on just the part that's relevant to the quaternions.

First, the call to `skimage.draw.ellipsoid(30,10,10)` actually returns an array of *boolean* values (True/False).  Now, either you're just copying code from somewhere else without understanding it, or you correctly understand this fact, because you've named the result `mask`, which is a typical name for an array of booleans.  But you should not expect to be able to rotate a bunch of True/False values.  What does that even mean?

Second, when you do `mask.reshape((23,483,3))`, you've just arbitrarily rearranged those True/False values into a different shape.  It's just a random coincidence that that was even possible because you chose `30` as one of the sizes for your ellipsoid, and that's divisible by 3.  When you input something into `quaternion.rotate_vectors`, it's looking for one axis of your array to have size 3 because those are supposed to represent the 3 dimensional location of a point or direction of a vector.  Here, you're just randomly grouping True/False values together into bunches of 3.  That doesn't mean anything.

Third, when you call `quaternion.rotate_vectors(rotation_x, arr3)`, the array `arr3` is still just an array of True/False values (print it out and take a look for yourself!), but it automatically gets converted into an array of 1.0s and 0.0s, which is why `rotate_vectors` even knows how to do anything with it.  You need to always think about what you're feeding into a function, and what that function is expecting.

Fourth, you reshape the result again with `rotd.reshape(63,23,23)`.  This is wrong for the same reasons as the earlier reshape, but in reverse.

Finally, your ellipsoid has size 30 in the x direction, size 10 in the y direction, and size 10 in the z direction.  The fact that those last two numbers are the same tells me that this ellipsoid id symmetric under rotation about the x axis.  But the rotation you're asking for is exactly a rotation through 90 degrees about the x axis.  So even if you correctly get a set of points to rotate, the surface will look exactly the same after that rotation.

I can tell that you're new to coding, so don't feel discouraged — we all need to start somewhere.  But you should try to slow down and actually understand what you're writing, piece by piece.  And actually look at your raw data to see if it makes sense.

As for just the basic task of rotating an ellipsoid, by looking at [the documentation](http://scikit-image.org/docs/dev/api/skimage.draw.html#skimage.draw.ellipsoid) I found [a really nice example of how to plot an ellipsoid](http://scikit-image.org/docs/dev/auto_examples/edges/plot_marching_cubes.html#sphx-glr-auto-examples-edges-plot-marching-cubes-py).  Modifying that example a little bit, I get this plot of the original ellipsoid (in blue) and the rotated ellipsoid (in red):

![rotating_ellipsoid](https://user-images.githubusercontent.com/1470769/53259346-dce05c00-369c-11e9-9d32-e654e061e44a.png)

And here's the code that does it:
```python
import numpy as np
import quaternion

import matplotlib as mpl
%matplotlib inline
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

from skimage import measure
from skimage.draw import ellipsoid

# Generate a level set about an ellipsoid in 3D
x, y, z = 3, 10, 16
ellip_base = ellipsoid(x, y, z, levelset=True)
center = np.array([x, y, z])

# Use marching cubes to obtain a surface mesh of these ellipsoids
verts, faces, normals, values = measure.marching_cubes_lewiner(ellip_base, 0)

# The ellipsoid is not centered on the origin, so let's change that
verts -= center

# verts is just an array of three-dimensional locations for the vertices, so we can rotate it with a quaternion
angle1 = 90
rotation = np.exp(quaternion.quaternion(1, 0, 0) * angle1*(np.pi/180) / 2)
verts_rot = quaternion.rotate_vectors(rotation, verts)

# Display resulting triangular mesh using Matplotlib.
fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111, projection='3d')

# Fancy indexing: `verts[faces]` to generate a collection of triangles
mesh = Poly3DCollection(verts[faces])
mesh.set_edgecolor('k')
ax.add_collection3d(mesh)

# Do that again, but with the rotated data
mesh = Poly3DCollection(verts_rot[faces])
mesh.set_alpha(0.25)
mesh.set_facecolor('red')
mesh.set_edgecolor('k')
ax.add_collection3d(mesh)

ax.set_xlabel("$x$")
ax.set_ylabel("$y$")
ax.set_zlabel("$z$")

max_axis = max(x, y, z)
ax.set_xlim(-max_axis, max_axis)
ax.set_ylim(-max_axis, max_axis)
ax.set_zlim(-max_axis, max_axis)

plt.tight_layout()
plt.show()
```

**Comment by Nirajkandpal** [comment]
**Hi Mike , 
                 Sorry for not being clear about my question . I do not have much experience with coding . Some part of the code  my adviser suggested me  that I write and I also used  different forums on internet where I got some hints .Originally the idea was to use scipy.ndimage.rotate which easily rotates the mask . Since I wanted to rotate the mask through all possible angles quaternion seemed the best way.  The following example code that works using scipy.ndimage.rotate as I saw has no error on running on jupyter notebook  . I also checked that this  method works on  original data and confimed it visually using a softwareParaview.**


`import numpy as np
import scipy
from scipy import ndimage
import skimage
from skimage import draw

dta = np.zeros((297,159,159))

mask = skimage.draw.ellipsoid(10,12,16)

x = 150
y = 75
z = 75


mask2 = scipy.ndimage.rotate(mask, 60 , axes = (0,1))

dta[x:x+mask2.shape[0], y:y+mask2.shape[1], z:z+mask2.shape[2]] = mask2
`


**The second code using quaternion instead of scipy.ndimage.rotate  gives me an error  which you previously also explained why .  The code is as follows .**

`import numpy as np
import scipy
from scipy import ndimage
import skimage
from skimage import draw
import quaternion

dta = np.zeros((297,159,159))

mask = skimage.draw.ellipsoid(10,12,16)

x = 150
y = 75
z = 75

angle1 = 90

rotation_x = np.exp([quaternion.quaternion(1, 0, 0) * angle1*(np.pi/180) / 2])

rotd = quaternion.rotate_vectors(rotation_x, mask)

dta[x:x+rotd.shape[0], y:y+rotd.shape[1], z:z+rotd.shape[2]] = rotd
`

**The error it gave is**

_ValueError : Input v does not have at least one dimension of length 3_

**Third set of code which I am currently using verts  in the code . The code is** 

`import numpy as np
import scipy
from scipy import ndimage
import skimage
from skimage import draw
import quaternion
from skimage import measure

dta = np.zeros((297,159,159))

mask = skimage.draw.ellipsoid(10,12,16)

verts, faces, normals, values = measure.marching_cubes_lewiner(mask, 0)

x = 150
y = 75
z = 75

angle1 = 0

rotation_x = np.exp([quaternion.quaternion(1, 0, 0) * angle1*(np.pi/180) / 2])

rotd = quaternion.rotate_vectors(rotation_x, verts)

dta[x:x+rotd.shape[0], y:y+rotd.shape[1], z:z+rotd.shape[2]] = rotd
`

**The error I get is **



> ValueError                                Traceback (most recent call last)
> <ipython-input-15-395ce433d460> in <module>()
>      23 rotd = quaternion.rotate_vectors(rotation_x, verts)
>      24 
> ---> 25 dta[x:x+rotd.shape[0], y:y+rotd.shape[1], z:z+rotd.shape[2]] = rotd
> 
> ValueError: could not broadcast input array from shape (1,2918,3) into shape (1,84,3)

**The the last line of each code dta[x:x+rotd.shape[0], y:y+rotd.shape[1], z:z+rotd.shape[2]] = rotd  is something i found in the stackoverflow and is to put the rotated mask(rotd) inside the example data (that is rotd inside dta).Hence last line of the code puts the mask at position x,y,z in the data(dta) which is very significant . This is something that is creating the main problem and I am not able to figure out how can I put the rotated array(rotd) inside the data(dta) when using quaternion.**


**After all this coding examples my main question is**

- **How can the rotated mask(rotd) be put inside example data(dta)  using quaternion just like in scipy.ndimage.rotate (First example code) ?  If I can rotate mask directly using quaternion probably it would work but as  you explained being boolean array could not be rotated .If I rotate verts in the code , it has very different shape which is not possible to put inside example data(dta)**

**Comment by moble** [comment]
Again, I understand that you're new to coding, so I'm not trying to be critical with what I'm about to say; I'm just trying to be helpful.  Remember when I said the thing about the *minimal* working example?  By showing me three different versions of your code, you're really moving farther away from the "minimal" *and* the "working" parts of my advice.

But more importantly, the idea behind a minimal working example is that you need to approach coding by breaking a problem down into smaller pieces.  You've got all this stuff about skimage, and ParaView, and this weird `dta` array, but none of *that* stuff is actually relevant to this quaternion package.  And it seems like you haven't actually understood the part of this that *is* about quaternions.  So you should split your problem up into smaller piece, take the quaternion part, and just look at it and try to understand it for a while.  In particular, try to follow my advice to "look at your raw data to see if it makes sense."  Did you look at `verts` or `rotd`?  Do you understand what data are actually being stored in those arrays?  Did you look at their shapes?  Their shapes are `(2918, 3)` and `(1, 2918, 3)`, respectively.  Does that make any sense to you?  Should `rotd` be able to fit inside of `dta`, even though its shape is `(297,159,159)`?  (The correct answer to each of these questions is "no".)

Okay, so even these questions need to be broken down into separate parts so you can understand them.  Start with the shape of `verts`: it has 2918 rows, and each row has 3 numbers.  That should be your hint that each row actually represents the three-dimensional location of a point on your ellipsoid.  For example, the first row in `verts` is `verts[0]`, which is
```python
array([2.220446e-16, 1.300000e+01, 1.700000e+01], dtype=float32)
```
This represents a point with (x,y,z) coordinates of roughly (0, 13, 17).

Maybe before you even try to rotate this, you should figure out how to view these points in ParaView.  Just do something like
```python
np.savetxt('verts.csv', verts, delimiter=',', header='x,y,z', comments='')
```
then open that file in ParaView, and click "Apply".  Then click "Filters">"Alphabetical">"Table to Points".  In the "Properties" tab, change "Y Column" to "y" and "Z Column" to "z", and click "Apply".  You should see a bunch of points shaped like an ellipsoid.

Hopefully, at this point you understand what all those numbers in `vert` actually mean.  If not, stop, go back, think about it, and play around with things until you do understand.

Now, the next step is to understand why `rotd` has that extra 1 in its shape.  The reason for this is that there's an important difference between the code example I gave you and the code that you're using.  You write
```python
rotation_x = np.exp([quaternion.quaternion(1, 0, 0) * angle1*(np.pi/180) / 2])
```
but I wrote
```python
np.exp(quaternion.quaternion(1, 0, 0) * angle1*(np.pi/180) / 2)
```
You have an extra set of square brackets, which makes that into a *list* — though that list happens to have just one item.  So what you get out of `np.exp` is actually a list of quaternions (with just one item).  You want "one quaternion", not "a list with one quaternion".  See the difference?  So get rid of those square brackets, and run your code again, and check on `rotd`.  You should find that its shape now is `(2918, 3)`, which is the same as the shape of `verts`, which is correct.  So if you want to see the rotated ellipsoid, just do the same thing, where you save it to file and open it in ParaView.
