### ISSUE TITLE
Memory leak when quaternion data type within pandas is converted to quaternion array

### ISSUE THREAD

**Issue by djbiega** [moble/quaternion#109]
**Describe the bug**
I've found that if I create a column within Pandas that is a `quaternion` data type and then try to convert into to an array using `as_quat_array` that there is a memory leak. 

**To Reproduce**
```python
import numpy as np
import quaternion
import random
import pandas as pd

df1 = pd.DataFrame(np.random.rand(10, 4), columns=['w', 'x', 'y', 'z'])
df1['quat'] = df1[['w', 'x', 'y', 'z']].values.tolist()
df1['quat'] = df1['quat'].apply(lambda x: np.quaternion(x[0], x[1], x[2], x[3]))
quaternion.as_quat_array(df1['quat'])
```

**Environment (please complete the following information):**
 - OS, including version: Windows 10 Pro
 - Numpy version (use `np.version.version`): 1.15.0
 - Quaternion version (use `quaternion.__version__`): 2019.3.16.19.47.45

**Comment by moble** [comment]
I'm not sure why you're saying this is a memory leak, but I'm actually getting a segmentation fault, which is much worse...

I don't mean to blame the user here, and you shouldn't be able to get segmentation faults if code is written well, but long story short: you're getting them because you're doing such weird things, and I probably won't bother to fix this because I don't think you actually want to be doing these things, and I don't think anyone else will either.  In fact, this segfault is actually coming from numpy (it's the first call inside that `quaternion.as_quat_array` function), so it would be more worthwhile filing a bug there.  And though I could check to make sure that numpy could handle whatever I'm sending its way, I don't think it's worth it.

First of all, unless you're actually sure you need pandas, you shouldn't be using it; you should try to stick with just plain numpy.  Pandas does extra things that complicate matters, and just aren't as clean as plain numpy (unless you need the extra functionality it provides, which can be very important).  For example, your code `df1[['w', 'x', 'y', 'z']].values.tolist()` returns a list of lists, but setting that equal to `df1['quat']` actually changes that to a pandas Series object.  That extra layer of confusion probably isn't helpful to you right now.  If you really need to use pandas, it's certainly possible — but skip it unless you know *why* you need pandas.

Now, the reason this is happening is because pandas has to do very weird things in order to allow it to keep various types of data in a single data series.  Before you run the last line of your code, you could check the `dtype` of your `df1['quat']` object:
```python
>>> df1['quat'].dtype                                                                                                       
dtype('O')
```
This `O` represents the "object" data type, which is really a catch-all that you should never use if you can avoid it.  Basically, `df1['quat']` is a pandas Series of `quaternion` objects, but pandas doesn't know that it can assume they'll always be quaternions, so it leaves them as generic "objects".  I'm guessing you ran into this, and so tried to change that `'O'` to "quaternion".  But `as_quat_array` is not the right way to do that (though I can see why you might think that it is).

The `as_quat_array` function is actually expecting an array of floats, or at least something that could be converted into an array of floats.  (In fact, that attempted conversion is the numpy function that's failing.)  And at one point, that's exactly what you have.  But then you jump through a couple hoops to *not* have that.  So to finally get to the point, here's what would have worked:
```python
import numpy as np
import quaternion
import pandas as pd

df1 = pd.DataFrame(np.random.rand(10, 4), columns=['w', 'x', 'y', 'z'])
df1['quat'] = quaternion.as_quat_array(df1[['w', 'x', 'y', 'z']].values)
```
Note that if you ask for the dtype now, you get a more sensible answer:
```python
>>> df1['quat'].dtype                                                                                                       
dtype(quaternion)
```
Of course, you could do it even more succinctly by skipping pandas:
```python
import numpy as np
import quaternion

q = quaternion.as_quat_array(np.random.rand(10, 4))
```

Then again, at a more fundamental level, what you _really_ should have done is just read the docstring on that function.  In ipython you do this by running `quaternion.as_quat_array?` (including the question mark).

---

P.S.  You don't need to `import random`, at least in your code snippet.  You don't use it, and numpy already has `np.random`.

**Comment by djbiega** [comment]
Ah I see my status as a newbie has been exposed. You are completely right that I did not need to use pandas here--i was only using it as a visual, and was only going to covert it to a np.array anyways. On a side note, could you explain how you knew it was a segmentation fault?

Thank you for the great explanation!

**Comment by moble** [comment]
> On a side note, could you explain how you knew it was a segmentation fault?

Memory leaks are usually hard to notice; you have to look for them.  If you're not looking for a memory leak, the only way you'd notice is if you're generating GBs of data that is leaking — but even then, the only thing to notice is usually just that your system slows down.

A segmentation fault, on the other hand, is drastic.  It causes your program (python, in this case) to immediately crash.  In the command line, it literally prints out "Segmentation fault".  In Jupyter, you'll just see a warning that the kernel is dead without any other explanation.
