### ISSUE TITLE
Add sphinx narrative and API docs

### ISSUE THREAD

**Issue by taldcroft** [moble/quaternion#110]
This package looks good and I'm excited about potentially using it. The current README is a start, but it would be very nice to have this on readthedocs and in particular have the API docs.

For instance I cannot infer from the existing docs what exactly the `add, subtract, multiply, divide` ufuncs do.  Are these just straight numeric operations or quaternion-specialized?

The driver here is to know how to replicate the `Quat` API using `quaternion` (http://cxc.cfa.harvard.edu/mta/ASPECT/tool_doc/Quaternion/).  Most important here is quaternion composition (where we use the `*` operator) and ["delta quaternions"](http://cxc.cfa.harvard.edu/mta/ASPECT/tool_doc/Quaternion/#Quaternion.Quaternion.Quat.dq)

Also, I appreciate the rant against Euler angles, but in our organization the spacecraft RA, Dec, and Roll are used *everywhere* (except NOT on the spacecraft itself) and there is no point in even making an argument.  So what I want in the docs is what convention is used in `quaternion` and how I can get to [equatorial (RA, Dec, Roll)](http://cxc.cfa.harvard.edu/mta/ASPECT/tool_doc/Quaternion/#Quaternion.Quaternion.Quat.equatorial)

Finally, as someone with experience in astropy and codes of conduct and inclusivity, you might consider toning down your docs.  I know you are passionate and opinionated (yay), but things like `... the best python installer, anaconda, ...` or `If you refuse to use conda, ...` are things we try to avoid.  Everyone has their own ideas about what is right, so a lot projects nowadays strive to be inclusive.

**Comment by moble** [comment]
> The current README is a start, but it would be very nice to have this on readthedocs and in particular have the API docs.

Thanks to work by @9999years, it's now on readthedocs.  Unfortunately I haven't been able to get the API docs running, which means the docs are basically empty (so I'm not going to advertise this fact yet).  I'd appreciate any help, because I'm honestly befuddled as to how readthedocs is supposed to work.

> This package looks good and I'm excited about potentially using it.

Thanks, glad to hear it!  Before I address your other points, I should just point out one important difference that I see: This package stores its quaternions in `[w, x, y, z]` order, whereas `Quat` stores it in `[x, y, z, w]` order.  I think this can easily be handled with a compatibility layer, but it's a potential major pitfall to watch out for.  One easy way to do it would be to stick to expressions using things like `q.x`, rather than `q[0]`.  More generally, there are lots of crazy and subtle differences in assumptions about how rotations should be applied, so I always recommend implementing basic tests to make sure your code does what you expect.

> I cannot infer from the existing docs what exactly the `add, subtract, multiply, divide` ufuncs do. Are these just straight numeric operations or quaternion-specialized?

I don't understand the distinction you're making here, but a relevant point is that — unlike a `Quat` — a `quaternion` is just the basic four-component object.  It isn't assumed to be a rotation, so it doesn't store any rotation information, and it behaves just like the standard quaternion algebraic object.  So if you have quaternions `p` and `q`, then `p+q` just represents another quaternion where each component is just the sum of the corresponding components of `p` and `q`.  (This is *usually* not a useful operation when you're only using quaternion for rotations, but that's not an assumption made by this package.)  Multiplication `p*q` is the full quaternion multiplication operation — so if `p` and `q` represent two rotations, then `p*q` represents the rotation given by their composition.  But since the quaternions form an algebra, you can also multiply by a scalar, as in `1.2*q`, which is just another quaternion where each component is 1.2 times the corresponding component of `q`.  Similarly, `p-q` is just `p + (-1)*q`, and `p/q` is just `p * q.inverse()`.

> Most important here is quaternion composition (where we use the * operator) and "delta quaternions"

To be explicit, it looks like we use the same `*` operator, so composition should work just the same.  As for the "delta quaternion" `dq`, since it satisfies `q2 = self * dq`, you can solve for it as `dq = self.inverse() * q2`.

>  So what I want in the docs is what convention is used in quaternion and how I can get to equatorial (RA, Dec, Roll)

I absolutely refuse to give names to any convention used in this package (because of the aforementioned variety of differences in assumptions, and the attendant ambiguity), but as it says in the docstrings, I assume the correspondence
```python
R = exp(alpha*z/2) * exp(beta*y/2) * exp(gamma*z/2)
```
Now, how you apply that quaternion as a rotation is up to you, but at least to me, that represents an initial rotation about `z` by `gamma`, followed by a rotation about `y` by `beta`, and a final rotation about `z` by `alpha` — where the vectors are fixed, and the angles are in radians.  If I understand correctly, the angles (ra, dec, roll) correspond to a rotation as
```python
R = exp(ra*pi*z/360) * exp((90-dec)*pi*y/360) * exp(roll*pi*z/360)
```
(Note that the initial rotation about `z` by `roll` is equivalent to a final rotation about the line of sight.)  If that's correct, then the translation should be pretty easy — something like
```python
def euler_to_equatorial(alpha_beta_gamma):
    ra_dec_roll = np.degrees(alpha_beta_gamma)
    ra_dec_roll[..., 1] = 90 - ra_dec_roll[..., 1]
    return ra_dec_roll
```
Then, you could even do something like
```python
def as_equatorial_degrees(q):
    return euler_to_equatorial(as_euler_angles(q))
```

**Comment by taldcroft** [comment]
@moble - excellent, thanks for the explanations.  This is exactly the sort of thing that would help users in the narrative docs, and now it's written!  :smile:

The convention we use (and I *think* is most typical in astronomy) is ECI (e.g. J2000, https://en.wikipedia.org/wiki/Earth-centered_inertial) where RA=Dec=0 is the x-axis.  So I think it is rotation of roll about X, rotation about Y by -Dec and rotation about Z by RA.  (Yes, conventions and signs are always a pain and the only way to be sure for me is writing tests to ensure it matches what we're using now).

**Comment by taldcroft** [comment]
Right now the readthedocs entry is just empty as far as I can see.

**Comment by taldcroft** [comment]
And about tone, just looking again at the [Euler angles are horrible](https://github.com/moble/quaternion/wiki/Euler-angles-are-horrible), I'll go one step further and say I actually find this statement *presumably because you interact with very old and unintelligent people who insist that you speak their idiotic language* to be offensive because you are talking precisely about me.  So I kindly request you remove those (really unnecessary) editorial aspersions.

**Comment by duetosymmetry** [comment]
@moble It is helpful to look at the build log on rtd. At the time of writing, here is the latest one from quaternion: https://readthedocs.org/api/v2/build/9081096.txt . Search for the string `WARNING: autodoc: failed to import module 'latest'; the following exception was raised:` to try to debug what's going on. I don't know why it's trying to load things named `latest`, presumably some magic in your `conf.py`.

I can report that your docs successfully build locally.

I can also report that I got rtd to work (though with some failures along the way) [for this project](https://qnm.readthedocs.io/en/latest/). If it's any help you can take a look at [the docs directory there](https://github.com/duetosymmetry/qnm/tree/master/docs) (and the only other rtd-specific file, up in the root, [.readthedocs.yml](https://github.com/duetosymmetry/qnm/blob/master/.readthedocs.yml))
