### ISSUE TITLE
Add Quaternion Matrices and quaternion rates matrices

### ISSUE THREAD

**Issue by pcmagic** [moble/quaternion#113]
the following two kinds of matrixs are very usefull for dynamic simulation. 

![image](https://user-images.githubusercontent.com/9511122/57489178-8fe04f00-72b5-11e9-95f2-2d13a8846dd7.png)

![image](https://user-images.githubusercontent.com/9511122/57489223-ac7c8700-72b5-11e9-8190-83e94f311a3c.png)

**Comment by moble** [comment]
I'm actually really curious to understand *why* those would be useful objects.  I can't think of any way that those could be used, that couldn't also be done directly (and usually more efficiently) with quaternions.  For example, the quaternion matrix requires four times as much storage as the quaternion alone; multiplication of two quaternion matrices will be slower than multiplication of two quaternions (because unless you specialize the multiplication, you'll need to compute four times as many components); rotation of a vector by the quaternion matrices will be much less efficient than either direct application of `q*v*q.conjugate()` or even application of `as_rotation_matrix` followed by multiplication.  As for quaternion rates, you can get the angular velocity from the quaternion by simply using quaternion multiplication — in fact, that's even implemented in this package [here](https://github.com/moble/quaternion/blob/0f9fa5220c7182c582ac588adb27b3a338a0ee3f/quaternion_time_series.py#L335).  You can also use the angular velocity to integrate directly to get a frame with that angular velocity — which is also implemented [here](https://github.com/moble/quaternion/blob/0f9fa5220c7182c582ac588adb27b3a338a0ee3f/quaternion_time_series.py#L203), and is the subject of [a paper I wrote](https://arxiv.org/abs/1604.08139).

I'm not saying there's definitely no use for them, but I'm skeptical, and I don't want to support code that encourages people to be less efficient, so I'll need to be persuaded.

**Comment by pcmagic** [comment]
Thanks a lot for your reply. 
I read the function _def angular_velocity(R, t)_ but I still confused that How can one calculate the quaternion rate (the change rate of the quaternion) from the rotate velocity. 

Consider a rigid body, let _e=(ex, ey, ez)_ is the frame fixed on the body. We can describe the rotation of the rigid body by using rotation velocity \Omega. We have _d(ei)/dt=\Omega*ei, ei={ex, ey, ez}_, here * means the cross product. 
And we can describe the frame using quaternion _q=(q0,q1,q2,q3)_. The rate of quaternion _dq/dt_ should be calculated from \Omega
![image](https://user-images.githubusercontent.com/9511122/57963409-1931fa00-7924-11e9-851a-1ae484bc97bb.png)
This is why I need those matrix. Is there any alternative and (or) efficient way to calculate them? 

Thanks again. 
    Best.

**Comment by pcmagic** [comment]
By the way, the article I'm using here is 

Diebel, James. "Representing attitude: Euler angles, unit quaternions, and rotation vectors." Matrix 58.15-16 (2006): 1-35.

**Comment by moble** [comment]
You can just solve Eqs. (146) and (147) directly.  In Diebel's notation, the first one gives you q̇ = q ω / 2, and the second one gives you q̇ = ω' q / 2.  Here, you treat the angular velocity vectors as quaternions with 0 in the scalar component.  So, for example, if you're given `omega` as a numpy array with three elements, you can turn it into a quaternion with `quaternion.quaternion(*omega)` [note the `*` in there], and then multiply and divide as usual:
```python
qdot = q * quaternion.quaternion(*omega) / 2
```
Or, if you're given `omegaprime`, you would do
```python
qdot = quaternion.quaternion(*omegaprime) * q / 2
```

I'll close this now, but if you find a real need for these, please just explain it to me and I can reopen it.

**Comment by pcmagic** [comment]
OK, This is work for me. Thanks a lot.
