### ISSUE TITLE
Squad return shifted values

### ISSUE THREAD

**Issue by The-any-Key** [moble/quaternion#118]
**Describe the bug**
When using squad the return quaternions value order is shifted. Input order is x,y,z,w and output order is w,x,y,z. So the return values are x=y, y=z, z=w and w=x.

**To Reproduce**
```python
import numpy as np
import quaternion
start_q=np.quaternion(0.45546597242355347, 0.00377300544641912, 0.007374392356723547, 0.8902146816253662)
end_q=np.quaternion(0.46072492003440857, 0.0038165694568306208, 0.00735193956643343, 0.8875043392181396)
squad_q=quaternion.squad(np.array([start_q,end_q]),np.array([0.0,1.0]),np.array([1.0]))
print(squad_q)
# Result: 
# x=0.0038165694568306208 
# y=0.00735193956643343 
# z=0.8875043392181396
# w=0.46072492003440857
```

**Expected behavior**
Expected result: 
x=0.46072492003440857 
y=0.0038165694568306208 
z=0.00735193956643343 
w=0.8875043392181396

**Environment (please complete the following information):**
 - Windows Version	10.0.17134 build 17134
 - Installation method: pip
 - Numpy version: 1.16.4
 - Quaternion version: 2019.6.11.17.26.3

**Comment by moble** [comment]
The problem seems to be that you're rewriting what the code actually outputs, and in doing so you are misinterpreting it.  If I actually run the code that you wrote above, the output is
```python
[quaternion(0.460724920034409, 0.00381656945683062, 0.00735193956643343, 0.88750433921814)]
```
This is precisely identical to `end_q` — which is what you should expect, because you're interpolating to the end time.

Now, it is true that this package stores the quaternion in (w, x, y, z) order, rather than (x, y, z, w) order, but this is the same for both the input and the output.  That is, we have
```python
>>> end_q.x == squad_q[0].x
True
>>> end_q.y == squad_q[0].y
True
>>> end_q.z == squad_q[0].z
True
>>> end_q.w == squad_q[0].w
True
```

---

As always, my general warning for anything involving rotations is that you should not expect any else to use the same conventions as you do, and so you need to test anyone else's assumptions against yours to see if they are the same.  I try to make this package as agnostic as possible when it comes to such conventions, but some choices must be made and this is one of them.  In this case, the thing you should check is the sign of the squares.  For example,
```python
>>> np.quaternion(1, 0, 0, 0) * np.quaternion(1, 0, 0, 0)
quaternion(1, 0, 0, 0)
```
tells you that the first element represents the scalar unit because it is positive, whereas
```python
>>> np.quaternion(0, 0, 0, 1) * np.quaternion(0, 0, 0, 1)
quaternion(-1, 0, 0, 0)
```
tells you that the last element represents one of the imaginary units because it is negative.  And you can check
```python
>>> np.quaternion(1, 2, 3, 4).w
1.0
>>> np.quaternion(1, 2, 3, 4).x
2.0
>>> np.quaternion(1, 2, 3, 4).y
3.0
>>> np.quaternion(1, 2, 3, 4).z
4.0
```
To see which element corresponds to which letter.  You should also check other products to make sure that this package's choices about the multiplication tables are the same as yours.  And otherwise, be sure to read the docstrings to make sure that you and I use the same conventions for, e.g., rotation matrices and Euler angles.

**Comment by The-any-Key** [comment]
My bad. Old habits just took over and expected np.quaternion(x, y, z, w).
