### ISSUE TITLE
Implementation of mean_rotor_in_intrinsic_metric

### ISSUE THREAD

**Issue by madphysicist** [moble/quaternion#120]
`mean_rotor_in_intrinsic_metric` is currently not implemented. I am fairly new to the language of quaternions, but it seems like the algorithm in `Markley, F. Landis, Yang Chen, John Lucas Crassidis, and Yaakov Oshman. "Average Quaternions." Journal of Guidance, Control, and Dynamics. Vol. 30, Issue 4, 2007, pp. 1193-1197` would be relevant here. Would you like for me to submit a PR? I would be happy to do so. My initial thought was to make yet another home-grown quaternion package, but I really like how you built the infrastructure here.

**Comment by moble** [comment]
I'd be open to an implementation of their algorithm, but the approach that [Markley et al.](https://ntrs.nasa.gov/search.jsp?R=20070017872) take isn't actually the same as optimizing with respect to the intrinsic metric.  In fact, it's more closely related to optimization with respect to the chordal metric, as I've defined it.

The object that Markley et al. call the "attitude matrix" A is the same thing returned by `quaternion.as_rotation_matrix`.  The squared Frobenius norm of the difference A(q)-A(q_i) is just the same as what you would write in this code as `8 - 8 (q_i * q.conjugate()).w**2` (where `.w` extracts the scalar component).  So minimizing the weighted sum of those squared Frobenius norms is equivalent to maximizing the weighted average of `(q_i * q.conjugate()).w**2`.  But the latter is  the squared cosine of half the angle required to rotate `q` onto `q_i`, whereas the intrinsic measure is just that angle itself, so the intrinsic mean would minimize this angle.  And even though the optima occur at the same values for a single `q_i`, once you optimize with many `q_i` values, you get different results.  So the mean defined by Markley et al. and the mean of the intrinsic metric really are different.

In fact, we can even go a little further and relate the Markley et al. metric to what I've called the "chordal" metric, which defines the distance between `q` and `q_i` to be essentially `np.norm(q-q_i)`, which is the same as `(q-q_i) * (q-q_i).conjugate()`.  The squared Frobenius norm of the difference A(q)-A(q_i) is precisely equal to `2 * np.norm(q-q_i) * np.norm(q+q_i)`, which is why I said that it's more closely related to the chordal metric — though, again, it's not the same.

It also seems to me that the "second flaw" that Markley et al. point out is easily fixed by simply flipping the signs of quaternions after (let's say) the first one to minimize the distance between those subsequent quaternions and the first one.  I wouldn't be too surprised if, with that additional step, the simple procedure that they reject is actually equivalent to their method.  But I'll have to ponder that further.

---

For what it's worth, [this paper by Moakher](http://epubs.siam.org/doi/abs/10.1137/S0895479801383877) predates Markley et al.'s and describes the same mean (and more, and does a really thorough job of it).  I'm not sure exactly what Markley et al. are suggesting, but from what Moakher says, I think that this simple bit of code will get the mean you're looking for, assuming `q_array` is a 1-dimensional array of quaternions:
```python
Rsum = np.sum(quaternion.as_rotation_matrix(q_array), axis=0) / q_array.size
Rmean = scipy.linalg.polar(Ravg)[0]
qmean = quaternion.from_rotation_matrix(Rmean)
```

**Comment by romainVala** [comment]
Hello
I am also new to quaternion, sorry then for my misunderstanding, 

I need to compute a weighted average of rotations, and we I give a try to mean_rotor_in_chordal_metric, but I get error, since my weights are not monotonously increasing. (I can not even order the weighted since some of them are equal)

what do I miss ?

Actually my use case is more complex, since I have general rigide transform (with rotations from different axis) so I understood I would need to go with dual quaternion, but I would like to understand it first with only rotations

many thanks for your help

**Comment by moble** [comment]
[The documentation for that function](https://quaternion.readthedocs.io/en/latest/Package%20API%3A/quaternion/means/) notes that the second (optional) argument `t` represents times that go into a spline to integrate the input quaternions; they're not just weights that multiply the quaternions directly.  If you want to manually weight each quaternion, just do that before you input the array into this function.  Something like this works:

```python
import numpy as np
import quaternion

q = quaternion.as_quat_array(np.random.normal(size=(17, 4)))  # Make up some random quaternions
q /= np.abs(q)  # Normalize them

weights = np.random.rand(q.size)  # Make up some random weights
wq = weights * q  # Weight the quaternions (they're no longer unit quaternions, but that's fine)

weighted_mean_rotor = quaternion.mean_rotor_in_chordal_metric(wq)  # This has unit norm
```

**Comment by romainVala** [comment]
thanks for you prompt response, 
I did not know one could just apply the weights on quaternion !
In the above example you do it on matrix, but I though one should stay with unit quaternion (to keep the geometry ... ?

**Comment by moble** [comment]
> In the above example you do it on matrix

I'm not sure what you mean by this.  In the example above, `q` is a numpy array with quaternion dtype, and `weights` is a corresponding set of scalar weights.  I don't see any matrices.

**Comment by romainVala** [comment]
sorry I refer to your first answer of this thread

```
Rsum = np.sum(quaternion.as_rotation_matrix(q_array), axis=0) / q_array.size
Rmean = scipy.linalg.polar(Rsum)[0]
qmean = quaternion.from_rotation_matrix(Rmean)

```

**Comment by moble** [comment]
Oh, that's referring to a different type of mean, which is what this issue was originally about.  (You should have opened a new issue because you're really talking about something completely different.  No big deal.)  That other method goes through the matrix representation, but is not relevant to the `mean_rotor_in_chordal_metric` function.

**Comment by dslemusp** [comment]
> [The documentation for that function](https://quaternion.readthedocs.io/en/latest/Package%20API%3A/quaternion/means/) notes that the second (optional) argument `t` represents times that go into a spline to integrate the input quaternions; they're not just weights that multiply the quaternions directly. If you want to manually weight each quaternion, just do that before you input the array into this function. Something like this works:
> 
> ```python
> import numpy as np
> import quaternion
> 
> q = quaternion.as_quat_array(np.random.normal(size=(17, 4)))  # Make up some random quaternions
> q /= np.abs(q)  # Normalize them
> 
> weights = np.random.rand(q.size)  # Make up some random weights
> wq = weights * q  # Weight the quaternions (they're no longer unit quaternions, but that's fine)
> 
> weighted_mean_rotor = quaternion.mean_rotor_in_chordal_metric(wq)  # This has unit norm
> ```

@moble Thx for the explanation. I am trying to implement this mwe but I get the following error in
`
weighted_mean_rotor = quaternion.mean_rotor_in_chordal_metric(wq)  # This has unit norm
`
`TypeError: Unknown input to QUATERNION_setitem`

**Comment by moble** [comment]
@dslemusp Sorry for the slow reply.  That error is due to an unexpected breaking change in numpy.  I've worked around it in the latest release of this package, 2022.4.3, which should be on PyPI in an hour or so, and conda later tonight.
