### ISSUE TITLE
Quaternion shape is empty

### ISSUE THREAD

**Issue by ascended121** [moble/quaternion#124]
**Describe the bug**
The `shape` property of quaternion returns an empty tuple. Tentatively listed as bug as this seems like undesirable behavior (at least to me).

**To Reproduce**
```python
import numpy as np
import quaternion

quat = np.quaternion()
print(quat.shape)
# ()
```

**Expected behavior**
It seems like the quaternion object should attempt to return some useful description of its contents, be it `(4,)` since its a container for 4 values or `(1,)` since its a singular quaternion. Generally it seems like `shape` can be used to determine the size of numpy objects, however it seems like I have to add specific code to handle the size of quaternion objects because it does define shape but doesn't return a useful value.

**Environment (please complete the following information):**
 - Ubuntu 18.04
 - Installed via pip
 - Numpy version (use `np.version.version`): 1.16.2
 - Quaternion version (use `quaternion.__version__`): 2019.6.18.12.39.44

**Comment by moble** [comment]
This is the correct behavior.  You shouldn't think of a quaternion as a container; you should think of it as a single number.  Just as complex numbers extend the real numbers, so too do quaternions extend the complex numbers.  And just as a complex number doesn't have a shape of 2, a quaternion should not have a shape of 4.

More precisely, because of how numpy works, the object you're looking at is actually an ["array scalar"](https://docs.scipy.org/doc/numpy/user/basics.types.html#array-scalars).  You can construct array scalars of the more familiar float and complex types like this:
```python
floa = np.array(1.2)
comp = np.array(1.2+3.4j)
```
(Note that I did *not* use square brackets as in `np.array([1.2])`; that's a completely different object.)  Just as with quaternions, these things have shapes:
```python
>>> floa.shape
()
>>> comp.shape
()
```
By your logic, these would either be `(1,)` and `(2,)`, or would both be `(1,)`.  But this is just not how numpy works.  It's not something I can change.

Of course, if you want to *use* quaternions or arrays of quaternions as containers of floats, there is a function to do that without copying data, but by just re-interpreting the bytes: `quaternion.as_float_array`.  The output is an array of type float, and its size ends in 4.

**Comment by ascended121** [comment]
@moble  I wasn't aware of array scalars but based on your response, what I'm seeing from the quaternion type makes sense. That's why I was hesitant to label this as a bug. Appreciate the thoughtful response!
