### ISSUE TITLE
quaternion.zero is a source of potential bugs

### ISSUE THREAD

**Issue by sfikas** [moble/quaternion#130]
**Describe the bug**
quaternion.zero can change to a value other than zero (see example below)
If there is some way to stop this object from being mutable, maybe it should be applied. Or at least make it harder to access by a user, for example change quaternion.zero to quaternion._zero (?) 
If this is used to initialize variables, terrible bugs may happen .. :)

**To Reproduce**
```python
import numpy as np
import quaternion

b = quaternion.zero 
print(b) 
b += 1 
print(quaternion.zero)                                                  
```

**Expected behavior**
The result will be:
quaternion(0, 0, 0, 0)
quaternion(1, 0, 0, 0)

**Environment (please complete the following information):**
 - OS, including version: Ubuntu 18
 - Installation method: pip
 - Numpy version: 1.13.3
 - Quaternion version: 2019.12.11.22.25.52

**Comment by moble** [comment]
Thanks for opening the issue.  You concerns are reasonable, and apply equally well to `quaternion.one`, `.x`, `.y`, and `.z`.  However, this is one of the most common and basic facts about coding in python, and changing this behavior would complicate too many other things.

1) I don't want to change this module in ways that will break code outside of it.  For example, I know that one common idiom is to express a rotation about the z axis as `exp(angle*quaternion.z/2)`, which is nice for a lot of reasons and not susceptible to this problem.  So I don't think it's a good idea to prefix these with underscores, or to change them into functions that return new objects with the relevant values.
2) Python does not have any *general* way to make things constant.
3) In principle, it would be feasible to create a subclass of quaternion objects, and override their various methods to make them immutable.  But making those objects play nicely with the usual quaternion objects *and numpy* is not something that I think I could complete in the next few decades.
4) It is actually [possible](https://mail.python.org/pipermail/python-ideas/2012-May/014969.html) to construct a class, and then define the module as an instance of that class — and alter the `__setattr__` method of the class to forbid modifying selected attributes like `zero`.  However, that's a very delicate operation that becomes more delicate the more things you have in your module.  And this module is large and complicated enough that supporting that would also be a nightmare, especially because it requires hacks that differ for different versions of python.
5) The nicest way to do this would be to override `quaternion.__getattr__`.  However, that's only supported on very old versions of python or on [python >=3.7](https://www.python.org/dev/peps/pep-0562/).  So until I drop support for python versions <3.7, I can't use this option.

Ultimately, this type of mutability is such a ubiquitous feature of python that all users (not just users of this package) simply need to be aware of it.  I'm sorry that this sounds so much like the old [doctor's advice](https://en.wikipedia.org/wiki/Smith_and_Dale#%22Dr._Kronkheit_and_His_Only_Living_Patient%22):

> You: It breaks when I do *this*.
> Me: Don't *do* that.

Unfortunately, that's the best I can do for now.  Sorry.  :/

**Comment by moble** [comment]
@kohlerjl explained what I was misunderstanding here.  This will be fixed momentarily.
