### ISSUE TITLE
32bits version

### ISSUE THREAD

**Issue by singladur** [moble/quaternion#131]
I am explaining my student quaternions and I'd like to use your library. However we use Anaconda 32bits and the actual version of this library is for 64bits. Could it be possible to create such a version of the library.

I know that the answer could be: use Anaconda 64bits and Python 64bits. But our staff is against this.

Thanks in advance.

**Comment by moble** [comment]
I don't actually control the anaconda builds; they are [done by conda-forge](https://github.com/conda-forge/quaternion-feedstock).  Unfortunately, conda-forge does not support 32-bit platforms.  (They have to build numerous versions of every package they support, and their polls found that almost no one uses 32-bit packages any more, so they don't spend their resources maintaining them.)

So something on your machine will have to build this package for you.  There are two basic ways to do this.

1. The simplest thing to do would be to try pip.  You can actually use pip along with conda.  Especially with newer versions of anaconda, this works very nicely.  To do this, just run `conda install pip`.  Then, you should be able to run `pip install numpy`, if you haven't already got numpy, and then `pip install numpy-quaternion`.  (Note that `pip install quaternion` actually gives you a completely different, much older package.)  This should build the package for you automatically.

2. You could also install from source yourself by [downloading this package](https://github.com/moble/quaternion/archive/master.zip), and then running `python setup.py install` from the directory you unzip (the one containing setup.py).

99% of the time, I would expect one of these to work without any extra effort.  But since you're using 32-bit systems, I wonder if there's something else extra-fancy about your setup.  If you get errors with the above, you'll need to do something more.  Basically, you need a C compiler installed, and you need python to know where that compiler is.  This might be as easy as `conda install gcc`, or `conda install conda-build`, or `brew install gcc` on OSX, or something like `yum install gcc python-devel` on centos, etc.  I hope it doesn't get this bad for you, but if it does, googling the error message and/or details about your system will usually show you how other people have solved the same problem on your system.

**Comment by singladur** [comment]
Thank you for the feedback and clear explanation.
I will  try to use pip as you suggest.

**Comment by moble** [comment]
Sure thing.  Feel free to reopen this, or ask another question if you think I might be able to help.  I'm very happy to think that the next generation will be learning about quaternions.  :)
