### ISSUE TITLE
Is there any way to call methods in a vectorized way?

### ISSUE THREAD

**Issue by cschlick** [moble/quaternion#132]
I have a quat array of:
Type: numpy.ndarray
Shape: (N,)
dtype = quaternion # (this package)

I want to run methods on all these objects. Currently I use:
```

import numpy as np

a_conj = np.array([q.conjugate() for q in a])
a_norms = np.array([q.norm() for q in a])
```

Is there a better way to do this?

Thanks for the package by the way.

**Comment by cschlick** [comment]
Actually I just realized that a.conjugate() works, but not a.norm().

Also a.inverse() does not work, so I also use a list comprehension for that.

**Comment by cschlick** [comment]
Ok, 1/a also works for the inverse. And since a.conjugate() works I can get the norm in a vectorized way. So I will close this.

**Comment by moble** [comment]
Unfortunately, because of the design of numpy, I don't have a lot of control over these sorts of things.  (Though they are changing the design, so hopefully things will be better in the future.)

Generally, it works out better to use methods from numpy, like `np.conjugate(a)` and `np.norm(a)` (note that this last one seems to be what you're looking for!).  I was able to add `np.normalized(a)`, which returns a new array where all the quaternions are normalized.

Also, though you didn't really ask about this, it may be useful to note that `quaternion.as_float_array` allows you to transform a quaternion array to an array of floats (with an extra dimension of size 4), at almost no cost.  For some purposes, this lets you manipulate the arrays using the standard numpy machinery for floats.  And since it just reinterprets the data rather than copying it, you can even perform manipulations in place if you know what you're doing, and then just use the original quaternions without even transforming back.

**Comment by cschlick** [comment]
Thanks for the comments. Finding that quaternion.as_float_array works on arrays of dtype=quaternion is something I had not realized and it very helpful.
