### ISSUE TITLE
`squad` in batched use?

### ISSUE THREAD

**Issue by kaufManu** [moble/quaternion#137]
Does `quaternion.squad` exist in a batched version? I.e., instead of supplying a quaternion array of shape `(T, 4)` could it handle an input of shape `(T, N, 4)`?

Looking briefly at the code of `squad` I think that the use of `searchsorted` could be problematic for a batched version. However, if we assume that the provided timings apply to all the `N`s equally, it might still be possible to implement a batched version?

I'm currently working around this by just looping over `N`. If there's any other way to circumvent that loop, I would be happy to adopt that solution, too.

**Comment by moble** [comment]
That commit should take care of this.  In particular, `t_in` and `t_out` need to be one-dimensional, and the *first* dimension of `R_in` still needs have size `T`, but any additional dimensions should be handled automatically.

**Comment by kaufManu** [comment]
That's awesome - thank you very much!

I just tried to test the commit by running `pip install git+https://github.com/moble/quaternion.git` in my conda env and gott the error `TypeError: Cannot change data-type for object array.` when using `from_rotation_vector` on a numpy array. I found [this old issue](https://github.com/moble/quaternion/issues/8) describing the some problem, so I'm thinking that I might have messed up my conda env somehow. Is there another recommended way how to test recent commits on the master?

**Comment by kaufManu** [comment]
Nevermind, I had a broken environment. Fixed by re-installing with administrator privileges. Thanks again for your help!

**Comment by moble** [comment]
@kaufManu I'm glad to hear it's working for you, but I'm worried about this "administrator privileges" thing.  You should really never have to do that, especially if you're using conda.  Conda only ever installs things in your user directory (unless you specifically tell it otherwise, which you shouldn't).  Installing anything related to python with administrator privileges could mess up your OS, and shouldn't help with any problems you have when working specifically with python.  It's more likely that your PATH just isn't getting set correctly, somehow.  Somewhere very near the beginning of PATH, it should point to your conda installation directory (which should be in your user directory), and that should handle everything related to python — python, ipython, jupyter, pip, etc.

**Comment by kaufManu** [comment]
Thanks for letting me know and the additional explanation! My message was a bit imprecise. I noticed that when I uninstalled some packages it couldn't remove some temp directories because of "Permission denied" errors (I'm on Windows). I thought executing the Anaconda prompt with admin rights would solve it, but it turns out another program was for some reason using the same folder so conda couldn't delete that folder. So, I wasn't installing to the root environment, just using admin rights for the Anaconda prompt.

After some more digging, this wasn't the problem however. I found that I had an old version of numpy (16.0) installed, which caused some problems with the newest version of numpy-quaternion. After upgrading numpy to 18.0 and re-installing numpy-quaternion, everything worked.

Apologies for the confusion, and thanks for your explanation!
