### ISSUE TITLE
Casting for np.vectorize

### ISSUE THREAD

**Issue by gsanc018** [moble/quaternion#141]
I cannot get np.vectorize to work. I want to do an element-wise operation on a matrix of quaternions... is this possible?

Thanks!
Giancarlo

**Comment by moble** [comment]
It would help if you could be more specific.  The relevant [ufuncs](https://numpy.org/devdocs/reference/ufuncs.html#available-ufuncs) should work (e.g., `np.exp(quat_array)` does element-wise exponentiation).  Also, you can efficiently convert any quaternion array to an array of floats, operate on them using the usual numpy approach, and then convert them back:
```python
float_array = quaternion.as_float_array(quat_array)
# do something here
quat_array = quaternion.as_quat_array(float_array)
```
Note that no copying of data is done here; it's just a reinterpretation of the data, so it's very fast.

**Comment by gsanc018** [comment]
Well I'm trying to project a quaternion to the space of 'Non-negative qauternions' and the mapping is given below
```
def proj_stokes(q):
  J = 0.5*np.array([[q.real+q.imag[1], q.imag[2]+q.imag[0]*1j], [q.imag[2]-q.imag[0]*1j, q.real-q.imag[1]]])
  w,v = np.linalg.eig(J)
  J = v@np.diag(np.maximum(np.real(w),0))@np.conj(v.T)
  S = [np.real(J[0,0]+J[1,1]), 2*np.imag(J[0,1]), np.real(J[0,0]-J[1,1]), 2*np.real(J[0,1])]
  return np.quaternion(*S)
```

Can we vectorize like this?
```
proj_stokes_mat = np.vectorize(proj_stokes,otypes=[np.quaternion]) #this doesn't seem to work, can we figure out why? maybe otype needs to be set?
```


I'm trying to get this to work so i don't have that for loop going through each entry of M.

```
def nnq_mat(n=10, m= 10):  
  M = np.random.uniform(-1,1,(n*m, 4)) # Create random Stokes vector  
  M = quaternion.as_quat_array(M).reshape((n,m)) #reshape to n by m quat matrix
  

  #project to nonnegative quat matrix
  P = np.array([[np.quaternion(0,0,0,0) for i in range(m)] for j in range(n)], dtype=np.quaternion)
  print(type(P))
  for i in range(n):
    for j in range(m):
      P[i,j] = proj_stokes(M[i,j]) 
  return P
```

**Comment by moble** [comment]
I don't know why vectorize doesn't work, but I never use it.  As it says in [the documentation](https://numpy.org/doc/stable/reference/generated/numpy.vectorize.html), vectorize doesn't have much effect on performance; it's basically syntactical sugar.  It doesn't move loops into C or use fancy processor instruction sets.  My guess is that your loop's performance is dominated by `np.linalg.eig`, and still would be with `np.vectorize`.

However, since all the functions you're using can handle multi-dimensional arrays, which actually does move loops into C/Fortran code, you should use their capabilities.  That is, use the built-in vectorization of `np.linalg.eig`, etc., to do the computation.  I think this is equivalent to your code, but handles individual quaternions and arrays of quaternions of arbitrary shape:
```python
def proj_stokes(q):
    J = np.empty(q.shape+(2,2), dtype=complex)
    q = quaternion.as_float_array(q)
    J[..., 0, 0] = 0.5 * (q[..., 0] + q[..., 2])
    #J[..., 0, 1] = 0.5 * (q[..., 3] + 1j * q[..., 1])  # `eigh` doesn't bother to look above the diagonal
    J[..., 1, 0] = 0.5 * (q[..., 3] - 1j * q[..., 1])
    J[..., 1, 1] = 0.5 * (q[..., 0] - q[..., 2])
    w, v = np.linalg.eigh(J)
    S = np.empty_like(q)
    J = v * np.expand_dims(np.clip(w, 0, None), -2) @ np.swapaxes(np.conjugate(v), -2, -1)
    S[..., 0] = np.real(J[..., 0, 0] + J[..., 1, 1])
    S[..., 1] = 2 * np.imag(J[..., 0, 1])
    S[..., 2] = np.real(J[..., 0, 0] - J[..., 1, 1])
    S[..., 3] = 2 * np.real(J[..., 0, 1])
    return quaternion.as_quat_array(S)
```
Note that I changed `eig` to `eigh` because your J matrix is Hermitian.  The `eigh` function is faster and returns purely real eigenvalues, which eliminates the call to `np.real`.  Also, constructing a diagonal matrix just to multiply it is inefficient; just insert a new axis and use regular multiplication.  All other changes are just to support extra dimensions.

The usual downside of using numpy — specifically, a lot of temporary storage is used that isn't strictly necessary — may be a problem if the arrays are huge.  If you find that it actually matters, this can be avoided by moving the innards of this function (everything *between* the `as_float_array` and `as_quat_array` calls) into numba.
