### ISSUE TITLE
as_rotation_matrix should always auto-normalize

### ISSUE THREAD

**Issue by willwray** [moble/quaternion#147]
This is not a correctness bug.
The bug is unnecessary code duplication and a possible performance bug.
The current implementation of quaternion to 3x3 rotation matrix uses this computation:

```
        n = q.norm()
        if n == 0.0:
            raise ZeroDivisionError("Input to `as_rotation_matrix({0})` has zero norm".format(q))
        elif abs(n-1.0) < _eps:  # Input q is basically normalized
            return np.array([
                [1 - 2*(q.y**2 + q.z**2),   2*(q.x*q.y - q.z*q.w),      2*(q.x*q.z + q.y*q.w)],
                [2*(q.x*q.y + q.z*q.w),     1 - 2*(q.x**2 + q.z**2),    2*(q.y*q.z - q.x*q.w)],
                [2*(q.x*q.z - q.y*q.w),     2*(q.y*q.z + q.x*q.w),      1 - 2*(q.x**2 + q.y**2)]
            ])
        else:  # Input q is not normalized
            return np.array([
                [1 - 2*(q.y**2 + q.z**2)/n,   2*(q.x*q.y - q.z*q.w)/n,      2*(q.x*q.z + q.y*q.w)/n],
                [2*(q.x*q.y + q.z*q.w)/n,     1 - 2*(q.x**2 + q.z**2)/n,    2*(q.y*q.z - q.x*q.w)/n],
                [2*(q.x*q.z - q.y*q.w)/n,     2*(q.y*q.z + q.x*q.w)/n,      1 - 2*(q.x**2 + q.y**2)/n]
            ])
```

(while the batched computation that follows always `# Assume input q is not normalized`)

It is unnecessary to have two branches for normalized or not-normalized.
Note that the 1s on the diagonal effectively assume that the quaternion is normalized.
The computation should instead always use the homogeneous version for the diagonal terms:

```
        n = q.norm()
        if n == 0.0:
            raise ZeroDivisionError("Input to `as_rotation_matrix({0})` has zero norm".format(q))
        else
            return np.array([
                [q.w**2 + q.x**2 - q.y**2 - q.z**2,    2*(q.x*q.y - q.z*q.w),    2*(q.x*q.z + q.y*q.w)],
                [2*(q.x*q.y + q.z*q.w),    q.w**2 - q.x**2 + q.y**2 - q.z**2,    2*(q.y*q.z - q.x*q.w)],
                [2*(q.x*q.z - q.y*q.w),    2*(q.y*q.z + q.x*q.w),    q.w**2 - q.x**2 - q.y**2 + q.z**2]]
            ]) / n
```
Note that the division by `q.norm() = q.w**2 + q.x**2 + q.y**2 + q.z**2` is moved outside the array
(I expect that numpy instead multiplies by the reciprocal 1/n to change expensive element-wise
 divisions into cheaper multiply ops).

This rewrite should also be done for the batched version that follows,
both for consistency and for better performance.

**Comment by moble** [comment]
It may be surprising, but the existing versions are actually faster than the versions you suggest.  In fact, I coded up a couple options similar to what you've suggested, and they're both 10% to 15% slower than the existing code for either a single quaternion or more than ~1,000 quaternions — and within the uncertainty for everything in between.  (My use cases are usually just one quaternion or tens of thousands.)

It's hard to say for sure, but I suspect the reasons have to do with things like cache hits, numpy's imperfect efficiency, and such.  In my code, it creates a 3x3 array, computes each element (including more divisions than are strictly necessary), and returns the result.  In your code, it creates a 3x3 array, computes each element, then creates a *new* array, and computes each element again (dividing the first array's values by `n`).  This means the division can be vectorized more effectively, but multiple arrays have to be created.  On balance, this is evidently slower than my version.

For the batched version, remember that numpy operates on full arrays, rather than the more efficient way you would do it in C.  For example, when you have `q[..., 2]**2 + q[..., 3]**2`, numpy extracts `q[..., 2]`, creates a new array with the square of each element, does the same with `q[..., 3]`, then creates another new array with the sum of those two arrays — and so on.  The point is that when thinking about the speed of numpy expressions, you need to go beyond the usual arithmetic speed considerations, and account for array access and caching and so on.

> the 1s on the diagonal effectively assume that the quaternion is normalized.

This is true on the first branch, where we've already decided that we're going to treat the quaternions as if they are normalized; on the second branch the full expression is just `n/n`, and so correct in any case.  And since it's much more efficient to represent `1` than to retrieve `n` or compute, e.g., `q.w**2 + q.x**2`, it's better to stick with 1.

> I find no evidence that numpy does ever replace `array / scalar` with `array * (1.0 / scalar)`

Yeah, this is usually enabled at the C level by the `fast-math` flag (or `unsafe-math-optimizations` or most specifically, `reciprocal-math`), which I believe you could actually compile numpy to use, but is not enabled on the versions you might get from PyPI or anaconda, for example.  While it's true that the current code could be sped up a little by doing this manually, I don't think it's a good idea.  Basically, whatever the reasons against enabling these flags by default, I think I should respect them.

Plus, if this is really a bottleneck, people should probably look into using numba with code that can be tailored more specifically to their needs.

**Comment by willwray** [comment]
Thanks for the explanations of numpy array copies here.
(I'm predominantly a C++ coder getting back into numpy and its array-processing offshoots so have a good appreciation for memory access, caching, etc., though not the details of interpreted execution of numpy code.)

Given all you point out, I'd still suggest a single branch, pulling the norm-scaling factor inside the array but reciprocated to a multiplication:

```
    n = q.norm()
    if n == 0.0:
        raise ZeroDivisionError("Input to `as_rotation_matrix({0})` has zero norm".format(q))
    else
        s = 1 / n
        return np.array([
            [s*(q.w**2 + q.x**2 - q.y**2 - q.z**2),    2*s*(q.x*q.y - q.z*q.w),    2*s*(q.x*q.z + q.y*q.w)],
            [2*s*(q.x*q.y + q.z*q.w),    s*(q.w**2 - q.x**2 + q.y**2 - q.z**2),    2*s*(q.y*q.z - q.x*q.w)],
            [2*s*(q.x*q.z - q.y*q.w),    2*s*(q.y*q.z + q.x*q.w),    s*(q.w**2 - q.x**2 - q.y**2 + q.z**2)]]
        ])
```

**Comment by willwray** [comment]
I guess there's also the option to rewrite using explicit numpy function calls with `out=in` parameter
to perform the operations in-place (at least it looks like that's the case).
That may be more worthwhile for the batched versions, to avoid those temporary working arrays.

For example, the matrix-quaternion algorithm only has a batched version.
To implement copysign from the first row a batch of matrices to a (same-size) batch of vectors
I tried this, `np.copysign( q[..., :] , Q[..., 0, :], q)`, with `q` target repeated as `out` param.
This seems to work as intended, though I'm not certain if it does work in-place and avoid a copy.

**Comment by willwray** [comment]
Or, in-place using `*=` 

```
  n = q.norm()
  if n == 0.0:
      raise ZeroDivisionError("Input to `as_rotation_matrix({0})` has zero norm".format(q))
  R = np.array([
      [q.w**2 + q.x**2 - q.y**2 - q.z**2),    2*(q.x*q.y - q.z*q.w),     2*(q.x*q.z + q.y*q.w)],
      [  2*(q.x*q.y + q.z*q.w),    q.w**2 - q.x**2 + q.y**2 - q.z**2,    2*(q.y*q.z - q.x*q.w)],
      [  2*(q.x*q.z - q.y*q.w),    2*(q.y*q.z + q.x*q.w),    q.w**2 - q.x**2 - q.y**2 + q.z**2]]
  ])
  if abs(n-1.0) >= _eps:  # Input q is not exactly normalized
      R *= (1 / n)
  return R
```

**Comment by moble** [comment]
To summarize my position: these are micro-optimizations that would surely represent a small fraction of the total time in any realistic application, and reproducibility tips the scales in favor of keeping existing code.
