### ISSUE TITLE
Multiplication between quaternion and vector

### ISSUE THREAD

**Issue by buschbapti** [moble/quaternion#151]
Hi,

I am trying to use this package for spatial transformation. When doing a quaternion multiplied by a vector, I am hoping to get a vector as a result corresponding to the vector rotated by the quaternion orientation. As an example:

```
rot = np.quaternion(0.70710678, 0.70710678, 0., 0.)
pos = np.array([4,5,6]);
```

expected result of `rot * pos` should be `np.array([4,-6,5])`. Instead it produces:

```
array([quaternion(2.82842712, 2.82842712, 0, 0),
          quaternion(3.5355339, 3.5355339, 0, 0),
          quaternion(4.24264068, 4.24264068, 0, 0)], dtype=quaternion)
```

which I can't really comprehend. Could you clarify whether this is expected? Thanks in advance.

**Comment by moble** [comment]
There are several points to note here.

First, just at a purely mathematical level, when you "multiply" a quaternion and a vector, you actually have to "promote" the vector to *be* a quaternion; multiplication of quaternions and vectors is not actually defined mathematically.  But there's a canonical map from vectors to quaternions, where you basically just put a 0 in front of the vector components.  So you need something more like

```python
pos = np.array([0,4,5,6]);
```

This is sometimes called a "pure-vector" quaternion.

Second, what you've actually done here is just define an array of four (previously three) numbers.  So when you ask numpy to multiply `rot` by this array, it just multiplies `rot` by *each* of the four numbers.  What you actually *want* to do is define `pos` to be a quaternion:

```python
pos = quaternion.quaternion(0,4,5,6)
```

(Or you could use the `quaternion.as_quat_array` function if you have more than one quaternion to create.)

Third, this package treats quaternions *as quaternions*, rather than as the rotations they represent.  This is important because there really is a difference: quaternions form a ["double cover"](https://en.wikipedia.org/wiki/Covering_group#Examples) of the rotation group, meaning that they really are fundamentally different, so they really can't be treated the same in general.  And more generally, there are applications of quaternions where they're used for more than just rotation matrices.  But when you multiply a quaternion by a "pure-vector" quaternion, you get a general quaternion back — it doesn't represent a vector yet.  What you need to do is multiply on the right by the inverse rotation quaternion:

```python
rotated_pos = rot * pos * rot.inverse()
```

Fourth, this is now a "pure-vector" quaternion.  So if you just want the vector components, you need to ask for them:

```python
rotated_pos.vec
```

Finally, now that you understand how this package actually works, you could have avoided all this by just using `quaternion.rotate_vectors`:

```python
rotated_pos = quaternion.rotate_vectors(rot, np.array([4,5,6]))
```
