### ISSUE TITLE
No module named 'quaternion.numpy_quaternion'

### ISSUE THREAD

**Issue by kaif2100** [moble/quaternion#155]
I'm trying to install numpy-quaternion:

pip install numpy-quaternion
...
Successfully installed numpy-quaternion-2020.11.2.17.0.49

but then it fails when I try to import it:
![image](https://user-images.githubusercontent.com/44539494/101277798-f26a3b80-37c7-11eb-8b47-abd082b4c51f.png)
I have checked the folder with `__init__.py` and there is no numpy_quaternion.py file

I use
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
np.version.version '1.18.1'

**Comment by moble** [comment]
> I have checked the folder with `__init__.py` and there is no numpy_quaternion.py file

It shouldn't be `numpy_quaternion.py`; with your setup it looks like it should be `numpy_quaternion.cp38-win32.pyd`.  (The "win32" part depends on your python version and system details.)  That file is provided inside the ["wheel"](https://realpython.com/python-wheels/) file that [pip downloads](https://files.pythonhosted.org/packages/51/e7/d52668f43bea4cb6f0db71df791d6a0977e35752c85b4bb904957d3c4364/numpy_quaternion-2020.11.2.17.0.49-cp38-cp38-win32.whl) when you ask for `numpy-quaternion` on a win32 system.  In fact, the complete list of files in that directory should be

```
__init__.py
calculus.py
means.py
numba_wrapper.py
numpy_quaternion.cp38-win32.pyd  # or "win_amd64" instead of "win32"
quaternion_time_series.py
```

Can you check that those files are in there?  If not, there is something wrong with your installation.

I don't actually have direct access to any windows machines, but Github Actions lets me try this on a 64-bit version, and [it works fine](https://github.com/moble/quaternion/runs/1507318540#step:3:67).


> I'm trying to install numpy-quaternion:
> 
> pip install numpy-quaternion

One problem with using `pip` directly is that it may be unrelated to whatever version of python you actually use.  So it might look like it successfully installed, but whatever you installed is actually sitting in some weird directory that your python doesn't actually know about.  One of the main core developers of python itself says that [you should always use `python -m pip` instead](https://snarky.ca/why-you-should-use-python-m-pip/), which is why that's what I recommend  in [the installation instructions](https://github.com/moble/quaternion#quickstart).

To be sure that this isn't what you're running into, you can try this in a shell:

```
python -m pip install --upgrade --no-deps --force-reinstall numpy-quaternion
python -c 'import numpy as np; import quaternion'
```

If that raises an exception like the one above, it means there's something wrong with your installation of python itself.  If not, it means that whatever version of python you're using in the shell is different from whatever `pip` version you get and/or the version of python that your Jupyter notebook is using.

**Comment by kaif2100** [comment]
I deleted it and tried as you suggested. There is file numpy_quaternion.cp38-win32.pyd in quaternion's folder, but it still gives the error \0/
![image](https://user-images.githubusercontent.com/44539494/101319853-b1c7fc00-3873-11eb-8097-1583ed7dc9af.png)

**Comment by moble** [comment]
So your python can find `quaternion/__init__.py`, but cannot find or just ignores `quaternion/numpy_quaternion.cp38-win32.pyd` in the same folder.  Evidently there's something very wrong with your python installation.

I can imagine there *might* be something weird about your `sys.path`.  Or maybe pip thinks it's supposed to install win32, but python is looking for win_amd64.  But one way or another, this installation of python is seriously messed up.

If you have a compiler, you could build the package yourself: download the code, change to the code directory, and run `pip install .` (including that `.` at the end).

Or you could try again with numba.

Or you could use the different (but closely related) [`quaternionic` package](https://github.com/moble/quaternionic).  This relies on numpy and numba, but doesn't use a C extension.

**Comment by kaif2100** [comment]
Seems, it was true about broken python. I've fully reinstalled it and everything works now
Thanks :)

**Comment by nathanielvirgo** [comment]
In case it helps someone else: I had a similar error to this - after installing numpy-quaternion I got an error "ModuleNotFoundError: No module named 'quaternion'".

It turns out this was because I had also installed a package called "quaternion", probably by accident when I was trying to install numpy-quaternion previously. I could fix the problem by runnning

```
python -m pip uninstall quaternion
```

and then, after that, running

```
python -m pip install --upgrade --no-deps --force-reinstall numpy-quaternion
```

It really seems I had to do both of those things, in that order, before it would work.
