### ISSUE TITLE
Multiplication with custom type raises TypeError instead of returning NotImplemented

### ISSUE THREAD

**Issue by Lee-000** [moble/quaternion#159]
Hi,
I'm writing a custom class, and I want to implement the `__rmul__()` method which supports multiplying with numpy quaternion.
But when numpy quaternion multiplies a custom type, it directly raises `TypeError` without calling the  `__rmul__()` function of the custom type.

```python
>>> import quaternion
>>> class A:
...     def __init__(self, data: float):
...         self._data = data
...     def __rmul__(self, other):
...         return other * self._data
...
>>> a = A(2)
>>> 2 * a
4

>>> q = quaternion.quaternion(1, 2, 3, 4)
>>> q * a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Binary operation involving quaternion and \neither float nor quaternion.
```
I was wondering if you could return `NotImplemented` instead of raising `TypeError` when numpy quaternion multiplies an unknown type so that the `__rmul__()` method of the custom type could be called.

Thank you for your time.

**Comment by moble** [comment]
Good idea.  Thanks!

**Comment by moble** [comment]
FYI: The updated version of this package was available on PyPI (pip) right when this issue was closed, but the conda-forge build ran into a silent bug.  It's fixed now, and the final build [is running](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=292000&view=results), so the version with this change should also be available via conda within about half an hour.
