### ISSUE TITLE
Quaternion Conda Package has bad Numpy Requirements.

### ISSUE THREAD

**Issue by Skylion007** [moble/quaternion#161]
**Describe the bug**
When freshly install the conda package, the conda requirements for the new conda numpy-quaternion release allow older versions of Numpy (specifically numpy-1.20.1). This is incompatible with the latest release and give this error when import numpy-quaternion. 
```
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
```
The conda package should be updated to explicitly forbid this (by requiring a higher version of Numpy to install the latest quaternion package).

**To Reproduce**
```python
import numpy as np
import quaternion
```
In this case, the requirements for habitat_sim's conda will allow this to package resolution to occur without error.

**Expected behavior**
It should cause a package conflict and either require numpy to be higher reversion or use an older numpy-quaternion if the specs allow.

**Environment (please complete the following information):**
 - OS, including version Ubuntu Colab
 - Installation method (conda, pip, or compiled from source) COnda
 - Numpy version (use `np.version.version`) numpy-1.20.1
 - Quaternion version (use `quaternion.__version__`)     quaternion-2021.3.17.16.51.43|   py37h5e8e339_0          88 KB  conda-forge

**Comment by moble** [comment]
> older versions of Numpy (specifically numpy-1.20.1)

1.20.1 is the current release of numpy (released just 34 days ago).  I can't reproduce any issue here with a fresh install.

---

It would have been helpful if you had included the error message here, but looking at your other issue, I see that it includes this:

```
ImportError: numpy.core.multiarray failed to import
```

Search for that error, and you'll see that it's an issue with numpy and/or python's approach to packaging, which will creep up from time to time when you try to use numpy.  It cannot be avoided by downstream packages like this one.  This package just has the unlucky position of being the first thing that tried to use numpy after it was loaded.

You'll also find that the solution is to run 

```
pip install --upgrade --force-reinstall numpy
```

(Or, presumably, the conda equivalent.)  And indeed, if I do that in your notebook after the initial installation step, the import works just fine.

So this is probably something caused by colab and/or the fact that you install a bunch of packages and then try to use them without restarting, or something like that.  Basically, python is getting confused about where to find things, but it has nothing to do with this package.
