### ISSUE TITLE
Dokumentation enhancement request

### ISSUE THREAD

**Issue by Wuhuuu2** [moble/quaternion#164]
Dear Michael,

thank you for your work so far!
Besides me trying to get a good gasp of how to work with quaternions (and not euler ;) ) I still do have some issues especially when it comes to integrating angular velocities.

Thus **I would like to request more documentation or an example on how to do perform integration of angular velocities with your package.**

### My tries:
I wanted to integrate a constant angular velocity of 90°/sec for 1 second.

In the following I have 2 ways:
1) Using qdot with euler 1st order integration
2) Your function integrate_angular_velocity.

Maybe it is wrong how I use it, but I did not find sufficient information to solve this. Furthermore, is there a way to use the first method with your package?

```python
import numpy as np
import quaternion

# Timestep and angular rates
dt = 1
p = 0
q = np.pi/2
r = 0

# initial vector
v0 = (1,0,0)
v0_q = np.quaternion(0,*v0)

# No rotation quaternion
e0,e1,e2,e3 = 1,0,0,0
e = np.array([e0,e1,e2,e3])

# quaternion derivative
G = np.array([[-e[1] , e[0] , e[3],-e[2]],\
              [-e[2] ,-e[3] , e[0], e[1]],\
              [-e[3] , e[2] ,-e[1], e[0]]])
edot = 1/2 * G.T @ np.array([p,q,r])
e = e + edot *dt
e /= np.sqrt(e[0]**2 +e[1]**2 +e[2]**2 +e[3]**2)
r_q = np.quaternion(*e)

# Roation of one timestep
v2_q = r_q * v0_q * r_q.conj()
v2 = quaternion.as_float_array(v2_q)[1:]

# Integration
t_q, v3_q = quaternion.integrate_angular_velocity( lambda w : np.array([p,q,r]), 0, dt, R0 = v0_q)
v3 = quaternion.as_float_array(v3_q[-1].normalized())[1:]


# Plotting
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
# Cartesian axes
ax.quiver( 0, 0, 0, 2, 0, 0, color='red'  ,linestyle='dashed') #, color='#aaaaaa'
ax.quiver(0,  0, 0, 0, 2, 0, color='green',linestyle='dashed')
ax.quiver(0, 0, -1, 0, 0, 3, color='blue',linestyle='dashed')
# Vector before rotation
ax.quiver(0, 0, 0, *v0, color='k', label="initial")
# Vector after rotation
ax.quiver(0, 0, 0, *v2, color='orange', linestyle=':', label = "integrate qdot")
ax.quiver(0, 0, 0, *v3, color='y' , label="integration fct")
ax.set_xlim([-1.5, 1.5])
ax.set_ylim([-1.5, 1.5])
ax.set_zlim([-1.5, 1.5])
plt.legend()
plt.show()
```

**Comment by moble** [comment]
> trying to get a good gasp of how to work with quaternions (and not euler ;) )

Excellent!  That's what I'm here for.

---

First, just to be clear, your angular velocity is 90°/sec **about the positive `y` axis**.  The initial vector `v0` is just the unit vector in the positive `x` direction.  So after 1 sec you should expect it to end up as **a unit vector in the negative `z` direction**.

Now for the code, it looks like you're misunderstanding the inputs and outputs of that function.  [The docstring](https://quaternion.readthedocs.io/en/latest/Package%20API%3A/quaternion/quaternion_time_series/#integrate_angular_velocity) describes it as computing the "**frame** with given angular velocity".  Technically [a frame](https://en.wikipedia.org/wiki/Basis_(linear_algebra)#Ordered_bases_and_coordinates) is just a vector basis in a particular order, though in quaternions we also use it to mean a quaternion that rotates the standard basis onto some other frame.  Either way, a single direction vector can't describe a frame.  In particular, `R0` is [the "initial frame orientation"](https://quaternion.readthedocs.io/en/latest/Package%20API%3A/quaternion/quaternion_time_series/#parameters), not the initial vector.  From how you treated `e`, I gather that you want the initial orientation to just be `R0=quaternion.one` (which is the default, so you can just leave it out) rather than `R0 = v0_q`.  The second returned quantity is also the frame, which is more like your `r_q` parameter.  Your code should look like this:

```python
t_q, r3_q = quaternion.integrate_angular_velocity(lambda w: np.array([p,q,r]), 0, dt, R0=quaternion.one)
v3_q = r3_q[-1] * v0_q * r3_q[-1].conj()
v3 = v3_q.vec
```

If you run this, you find that `v3` is just `-z` up to numerical accuracy, which is the correct answer.

> I would like to request more documentation or an example on how to do perform integration of angular velocities with your package.

I don't really have time for that right now, but a general hacking tip is useful here: search the *tests* for the function you want to use.  In this case, the tests have [three examples](https://github.com/moble/quaternion/blob/7d82e9157d3da7c199f0980adc61d2327bd371ef/tests/test_quaternion.py#L1557-L1574) that run the three different possibilities noted in [the docstring](https://quaternion.readthedocs.io/en/latest/Package%20API%3A/quaternion/quaternion_time_series/#integrate_angular_velocity).

> is there a way to use [qdot with euler 1st order integration] with your package?

Obviously first-order Euler is low-order and not particularly stable.  But in this particular case, your integration is so simple and short that it will work pretty well if you take smaller steps.  In the code above, you just took one huge step, which is why you got such a big error.  Just make a loop with smaller steps:

```python
e = np.array([1.0, 0, 0, 0])
delta = 1e-3  # Time step size
t = 0
while t < dt:
    G = np.array([
        [-e[1] , e[0] , e[3],-e[2]],
        [-e[2] ,-e[3] , e[0], e[1]],
        [-e[3] , e[2] ,-e[1], e[0]]
    ])
    edot = 1/2 * G.T @ np.array([p,q,r])
    e += edot * delta
    t += delta
```

You can play around with `delta`.  As you decrease it, you should see `e` converge to the right answer, which is `[1, 0, 1, 0]/sqrt(2)`.

Of course, that `edot` expression is just a really ugly way of doing quaternion math, so I would *actually* use quaternions:
```python
omega = np.quaternion(0, p, q, r)
while t < dt:
    edot = quaternion.as_float_array(1/2 * omega * quaternion.as_quat_array(e))
```

[See also [this paper](https://arxiv.org/abs/1604.08139) for lots of discussion about practical methods (the best of which is implemented as the `integrate_angular_velocity` function).]

**Comment by roshambo919** [comment]
I'm trying to follow this thread...inverting this gives:
```
quaternion.angular_velocity([v0_q, v3_q], [0,dt])
# array([[-0.,  2.,  0.],
#        [ 0.,  2.,  0.]])
```
My thought was this should output the original angular velocity of `[0, np.pi/2, 0]`. I cannot seem to make sense of this result. Am I missing something fundamental here?

**Comment by moble** [comment]
I hadn't documented the `angular_velocity` function before because I thought it was a little more specialized than anyone would care about, but I've done so now: see [here](https://github.com/moble/quaternion/commit/20eb27d525f981ba9ab6fb57439af7a83ac36a23).

It looks like you've assumed that the input `R` argument is supposed to represent a vector function of time.  (You've disguised the vectors as `quaternion` objects, but they *represent* vectors, as you might have guessed since they all have 0 as the scalar part.)  But this would not be enough information to deduce an angular velocity.  In fact, there are infinitely many angular velocities that would give you those vectors at those instants of time.  Instead, `R` is supposed to be a quaternion function of time — and specifically a quaternion representing the *frame* at each instant.

So, following the above, if you do
```python
quaternion.angular_velocity(r3_q, t_q)
```
this gives you approximately the answer you expected.  It's only approximate because it's using a cubic spline, but if you decrease the spacing in time (`dt`), this will converge to the exact result.
