### ISSUE TITLE
squad documentation improvement and/or assumption checking

### ISSUE THREAD

**Issue by senselessDev** [moble/quaternion#166]
I was debugging quite some time to find out why the squad interpolation was giving me weird results. In the end it was caused by not fulfilling the following assumption

> The input R_in rotors are assumed to be reasonably continuous (no sign flips)

which is given in the squad documentation. Unfortunately, I was not reading carefully enough on the first read (written somewhere in a "wall of text") to notice that this is the case for my data and that the weird results were caused by that. So I would suggest to at least include a link/mention at this sentence to the unflip_rotors function. Because at least [the version of the documentation I was reading](https://quaternion.readthedocs.io/_/downloads/en/reorganize/pdf/) does not even have this function documented.

By judging from the design choices at other places, I think it is intentional that the unflipping is not directly included in the squad function. So I guess you don't like my preference of having that included. But what is your opinion on including a check of the assumption and generating a warning if it is not met?

**Comment by moble** [comment]
> somewhere in a "wall of text"

That's a bit rude.  That "wall of text" is shorter than your comment above.  I feel like you should be willing to read a little more than you expect me to read, especially when the function is working correctly and as described.  You just needed to read the first line of the second paragraph in that docstring.

Also, I don't know how you got that weird PDF link, but you should always read the documentation for whatever version you're actually using of any code.  The `unflip_rotors` function didn't exist at the time that was created.

Now, defaulting to unflipping is dangerous, because sometimes people really do want to have very different successive rotors.  And checking for it locks the user into behavior they may not want.  On the other hand, I have no problem adding an option to do the unflipping for the user, which should draw attention to this fact without changing the behavior of existing code.
