### ISSUE TITLE
Is it possible to make quaternion iterable?

### ISSUE THREAD

**Issue by Lee-000** [moble/quaternion#174]
Hi,
While I'm using quaternion, I found out that numpy quaternion is not iterable. So that a lot of operations are not very convenient, like converting a quaternion to a list, unpacking a quaternion.

```python
>>> from quaternion import quaternion
>>> q = quaternion(1, 2, 3, 4)
>>> list(q)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'quaternion.quaternion' object is not iterable
```
And another quaternion repo I know, [pyquaternion](https://github.com/KieranWynn/pyquaternion), supports iteration.
Is there any specific reason that numpy quaternion did not support this? If not, I was wondering if you could make quaternion iterable.

Thank you for your time.

**Comment by moble** [comment]
Iteration is a very inefficient solution to the problems you're indicating.  Remember that when dealing with numbers in python, you really should try to stick with numpy as much as possible.  In this case, you *could* use [`q.tolist()`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tolist.html).

Of course, I'm not actually encouraging making a *list* of the numbers in a quaternion, because lists are memory hogs and very slow.  Maybe what you really want is just a regular numpy array of `float`s.  In this case, it's *vastly* more efficient to just ["view"](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.view.html) the data in a quaternion array as `float` data, which can be done with [`quaternion.as_float_array(q)`](https://quaternion.readthedocs.io/en/latest/Package%20API%3A/quaternion/#as_float_array).  This is nearly instantaneous, involves no copying of memory, and leaves you with a numpy array, which is what you probably want.

If you can come up with a better example that really can't be solved very well without iteration, I'll certainly reconsider.  But in general, you should try to use numpy directly, which will never involve iteration over individual components of a quaternion.  While `pyquaternion` is a nice package, it's not designed for efficiency — which is one of the main goals of this package.  Generally, I don't want to encourage inefficient code, so I won't implement iteration without a good reason.

**Comment by Lee-000** [comment]
Thank you for your answer, which is very reasonable. Efficiency is indeed an important reason that we choose `numpy quaternion`. But the `q.tolist()` does not seem to work correctly. The result is still a quaternion.
```python
>>> from quaternion import quaternion
>>> q = quaternion(1, 2, 3, 4)
>>> q.tolist()
quaternion(1, 2, 3, 4)
```

**Comment by moble** [comment]
> `q.tolist()` does not seem to work correctly.

That's the correct behavior; I guess I just wasn't clear on what you were going for.  Using `tolist()` converts any array to a list of its elements, and those elements will have the same type as before — in this case, `quaternion`.  If you literally want a (possibly nested) list of the components of the quaternion, you can do `quaternion.as_float_array(q).tolist()`.  This will first convert the quaternion array to an array of `float`s, and then convert that to a list.  But again, you should really stay away from lists.
