### ISSUE TITLE
Add rotation conversion functions

### ISSUE THREAD

**Issue by hovren** [moble/quaternion#19]
Since quaternions are commonly used for representing rotations, I think having functions that convert a (unit) quaternion to a rotation matrix would be very useful.

The following Python snippet solves the task:

    def quat2rot(q):
        "Convert unit quaternion to rotation matrix."
        assert np.isclose(q.norm(), 1.0)
        R = np.array([
        [1 - 2*q.y**2 - 2*q.z**2,   2*q.x*q.y - 2*q.z*q.w,      2*q.x*q.z + 2*q.y*q.w],
        [2*q.x*q.y + 2*q.z*q.w,     1 - 2*q.x**2 - 2*q.z**2,    2*q.y*q.z - 2*q.x*q.w],
        [2*q.x*q.z - 2*q.y*q.w,     2*q.y*q.z + 2*q.x*q.w,      1 - 2*q.x**2 - 2*q.y**2]
        ])
        
        return R

I could write the patch myself, but I am unsure where it should go, or if there are any constraints that I am unaware of (numba support, etc). The `assert` statement to check for unit norm should probably be changed as well, or at least not throw an AssertionError.

It would also be useful to add the inverse function (rot2quat) and maybe other rotation representations like axis-angle or Euler angles.

**Comment by moble** [comment]
Okay, I've added the various functions.  I just implemented them in python, rather than at the C level, because the algorithms are straightforward but the python/numpy C API would make it a chore to write them.  I also chose a slow but (hopefully very) robust algorithm for converting from quaternions to rotation matrices... and it depends on scipy.  But hopefully these conversions won't be limiting anyone.

And as always, I reserve the right to offend anyone who chooses to use Euler angles.  :)

**Comment by hovren** [comment]
Great!

I do however think that an attempt to convert a non-unit quaternion should raise an exception (ValueError?), and not implicitly normalize. Since only unit quaternions are rotation representations, I think that is what I would expect.
