### ISSUE TITLE
osx-arm64 conda

### ISSUE THREAD

**Issue by anklebreaker** [moble/quaternion#190]
Would it be possible to release a build for osx-arm64 for conda (or at least no-arch)? Currently cannot install via conda using existing channels on a Mac M1 Apple Silicon

**Comment by moble** [comment]
The conda build is [handled by conda-forge](https://github.com/conda-forge/quaternion-feedstock), so unless they support it, I can't add a new architecture.  It can't be no-arch because this package actually includes a C extension that has to be compiled.

However, you can actually [use pip from within conda](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html).  (I still strongly recommend using conda, but reverting to pip only when necessary.)  And [it looks like](https://pypi.org/project/numpy-quaternion/#files) I am building pip wheels for osx-arm64.  So just activate your conda environment, and then use the pip command given in the README.

If pip doesn't think your requirements actually match one of the wheels, pip may try to build the package for you.  This might work with no further effort on your part, or you may need to `conda install gcc` or something like that.

Also note that [`quaternionic`](/moble/quaternionic) package, which is similar to this one, but uses numba instead of C, so it is no-arch.
