### ISSUE TITLE
Add a function to rotate vector with a quaternion

### ISSUE THREAD

**Issue by bakwc** [moble/quaternion#195]
I want to rotate a vector with a quaternion. And currently there is no builtin function for that. I suggest to add a builtin function to make a rotation with a single function, and not a 4-step operations.

**Comment by moble** [comment]
https://github.com/moble/quaternion/blob/c22f93840a7ab7391576085b92e2545583f9cb40/src/quaternion/__init__.py#L654-L711

**Comment by bakwc** [comment]
Oh, there is already exists this function. It should be probably added to readme. Sorry!

**Comment by moble** [comment]
README != docs

**Comment by bakwc** [comment]
Ok, thank you. Cool library!

**Comment by MoffKalast** [comment]
For anyone else that finds this and is wondering why the hell that workaround returns a quaternion array, this should be the actual code:

```
# v is a numpy array of [x, y, z]
def quaternion_mult(self, q, v):
    vout = (q * v * q.conjugate())
    return np.array([vout[0].w, vout[1].w, vout[2].w])
```

I think it would be helpful to add something of the sort to the object class, so that one can just do `quat_instance.mult(vector) ` and get a vector back as is fairly standard in most game engine quaternion libraries, instead of doing it this unintuitive roundabout way.

**Comment by moble** [comment]
A. Quaternion multiplication is a thing, and it's not the same as rotation.
B. What workaround are you talking about?
C. The function `quaternion.rotate_vectors` already exists, and does what you're trying to do — including returning a plain numpy array of vectors rather than quaternions — but does it correctly and usually *far* more efficiently.
D. A term like `vout[2].w` takes the scalar part of the `2` element of `vout`.  I have no idea what you're trying to do here, but I don't think that's what you want.
E. Here's a suggestion: Read what's written above and try it.  And maybe don't be a jerk.
