### ISSUE TITLE
angular_velocity() output format

### ISSUE THREAD

**Issue by wmcnally** [moble/quaternion#201]
I am trying to get angular velocity from an array of quaternions using the angular_velocity function. I pass an array of shape (n, 4) representing the sequence of quaternions for n time steps. The output has the shape (n, 3, 4). I was expecting (n, 3) representing the x, y, z components of angular velocity. What does the output represent? Thanks!

**Comment by moble** [comment]
The [docstring for that function is here](https://quaternion.readthedocs.io/en/latest/Package%20API%3A/quaternion/quaternion_time_series/#angular_velocity).  It says that the input `R` parameter is supposed to be a

> Quaternion-valued function of time evaluated at a set of times.

So instead of an array of `dtype=float` of shape `(n,4)`, you're supposed to pass in an array of shape `(n,)` with `dtype=quaternion`.  If you have an array `a` of `dtype=float`, you can get an array of `dtype=quaternion` very efficiently by using `quaternion.as_quat_array(a)`, and pass that as the first argument.  The output will then have shape `(n,3)` as expected.

**Comment by wmcnally** [comment]
ok thx!
