### ISSUE TITLE
Wrong quaternion norm implementation

### ISSUE THREAD

**Issue by Sujo1** [moble/quaternion#22]
The quaternion norm implementation actually gives the square of the quaternion norm as can be seen from the following simple code:
```
import numpy as np
import quaternion

qv = np.array([1,2,3,4], dtype = np.float64)
q = np.quaternion(1,2,3,4)

print(np.linalg.norm(qv), q.norm(), np.sqrt(q.norm()))
```
which results in:
```
5.47722557505 30.0 5.47722557505
```

**Comment by moble** [comment]
It's not wrong; it's just the choice I made.  I made that choice for consistency with another package I was using at the time.  I agree that including the square-root is more common, but some sources do give the norm as simply the sum of the squares.  You might also be interested in the `abs` method, which does take the square-root.

**Comment by moble** [comment]
For the record: I just realized that this choice for the definitions of `abs` and `norm` agrees with the same [functions in the `boost::math::quaternion` implementation](http://www.boost.org/doc/libs/1_66_0/libs/math/doc/html/math_toolkit/value_op.html).

**Comment by tazr** [comment]
Very confusing indeed. Why call "norm" something that is not a [norm](https://en.wikipedia.org/wiki/Norm_(mathematics))?

**Comment by moble** [comment]
> Renaming it to something like `ceyley_seminorm` would be an improvement in my opinion

Well, first of all, that would involve misspelling "Cayley".  Second, this is not a seminorm *as distinct from a norm* because it does not send any nonzero quaternion to zero; referring to it as a seminorm would suggest otherwise.

> Why call "norm" something that is not a norm?

Well, there are several reasons.  First, it actually is a norm — but there are different conventions for what precisely "norm" refers to [see my comments above, or the very wikipedia article that you linked to].  In particular, the wikipedia article you link to defines a norm for a vector space and while quaternions do form a vector space, they also do more than that: they form an [*algebra*](https://en.wikipedia.org/wiki/Algebra_over_a_field).  And specifically in the context of *algebras*, it is more common to use the word "norm" in reference to the squared version.

Second, as I said above, this is the choice consistent with the Boost implementation of quaternions, as well as python/numpy's implementation of complex numbers.

Third, because I don't code for the lowest common denominator, tazr; you should probably learn to read, code for yourself, or stop complaining.
