### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by andreydung** [moble/quaternion#29]
How do I rotate a vector, let's say (0, 0, 1), using the quaternion? I couldn't find the function in the documentations (there is a lots of quaternion manipulation, but is there a transform/apply function)?

**Comment by moble** [comment]
At the time of this writing, there is no specialized function (though I'll add one in the next week or two).  So the way to go for now is to just use quaternion multiplication.  For example, if you have a 3-vector `v` (as a list or numpy array, for example) you can convert it to a quaternion as
```python
V = quaternion.quaternion(0, *v)
```
Then you can rotate it as
```python
Vprime = R * V * R.conj()
```
[If you're not sure if `R` will be precisely normalized, you might want to use `R.inv()` instead of `R.conj()`.]  You can then get just the vector components as a numpy array with
```python
Vprime.vec
```

This, of course, is relatively slow because the operation count is higher than it needs to be (32 multiplies and 24 adds).  I can cut the operation count almost in half (18 multiplies and 12 adds) by using a specialized function.  I'll leave this open until I implement that.

**Comment by DrHibbitts** [comment]
Has there been any progress on this? the ability to apply Quaternions to vectors is likely to be a key component in any project that uses Quaternions.

**Comment by moble** [comment]
As I said above, it is currently possible, it's just that it could be made more efficient.  I've been trying to figure out the best approach, because numpy doesn't make this particular task very easy.

I will say that if you're interested in using the same quaternion to rotate multiple vectors — as opposed to using different quaternions for each rotation — it's most efficient to convert the quaternion to a rotation matrix (using `quaternion.as_rotation_matrix`), and then use numpy.

But achieving my original objective is proving more difficult than I had hoped.  I'll keep this thread posted with any developments.
