### ISSUE TITLE
as_spherical_coords(from_spherical_coords(*x)) != x

### ISSUE THREAD

**Issue by castle-bravo** [moble/quaternion#34]
I'm having trouble converting to quaternions from spherical coordinates and back. I'm not sure if this is from a gap in my understanding or a bug in the library.
```
>>> quaternion.as_spherical_coords(quaternion.from_spherical_coords(*np.array([0, pi])))
array([ 0.        ,  1.57079633])
```
I expected the output to be `array([ 0.        ,  3.14159265])`. I suspect this is a result of using two different spherical coordinate schemes for `from_...` and `as_...`, but I wasn't able to find the implementation of `as_...` in your source code to compare them.

**Comment by moble** [comment]
The short answer to your question is: the two functions `as_spherical_coords` and `from_spherical_coords` are not inverses, so you can't expect to get the same thing out as you put in.  Only one scheme is used for spherical coordinates, and what you're seeing is consistent with what I expect.

First, I should point out that I use the physics convention for the coordinates (theta, phi):

![](https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/3D_Spherical.svg/260px-3D_Spherical.svg.png)

In particular, both `(0, pi)` and `(0, pi/2)` represent the north pole.  In this sense, the result you're seeing is correct.

More precisely, if you do `help(quaternion.as_spherical_coords)` you'll see that `as_spherical_coords` returns coordinates to "the point on the sphere to which the input quaternion rotates the z axis", which is indeed what you're getting — it's just that spherical coordinates are singular at that point.  Alternatively, you could note that the `Returns` section of the docstring says that the returned (theta, phi) coordinates give the input rotation up to an arbitrary initial rotation about `z` — which is needed because spherical coordinates simply cannot represent an arbitrary rotation.

FYI: The implementation of `as_spherical_coords` is [here](https://github.com/moble/quaternion/blob/f3beabca101ed61c03ac2429e2fd276e14bf5fab/__init__.py#L396).  You will see that I define the spherical coordinates as just a subset of the Euler angles.  And if you then read the docstring for `as_euler_angles`, you will get an idea of what I think of Euler angles.

I could have made a different choice that would have been better for precisely the north and south poles, but I don't know that it actually matters.  If it matters to you, I suggest redefining the function along these lines:

```python
def as_spherical_coords(q):
    alpha, beta, gamma = as_euler_angles(q)
    if beta < 1e-15:
        return beta, alpha+gamma
    elif pi-beta < 1e-15:
        return beta, alpha-gamma
    else:
        return beta, alpha
```

You would need to test that because I may have gotten some signs wrong.  You might also want to make it work with general arrays of quaternions like the original function.  But this is complicated enough that I don't know any case where it would be worth the trouble.
