### ISSUE TITLE
Minor suggestion: allowing the use of integer (or why not?)

### ISSUE THREAD

**Issue by calocedrus** [moble/quaternion#40]
If I pass an array of `int` to `quaternion.as_quat_array` it will complain.
```python
import numpy as np
import quaternion
a = np.arange(12).reshape(3,4)
sin_a = np.sin(a) # no problem
quat_a = quaternion.as_quat_array(a) # AssertionError: assert a.dtype == np.dtype(np.float)
```
It is easy to fix by converting `int` to `float` or ensuring that floats are input, but there maybe some `quaternion` usage cases where the input array is `int` and should be kept as is, without the need for conversion or copy. Many maths functions in python and numpy accept integers as inputs, and though `as_quat_array` isn't a math function, is there a reason for requiring exclusively floats?
How about accepting `int` as well?

**Comment by moble** [comment]
Keeping the array as integers would require creating all new quaternion_int datatypes, because that's just not how statically typed languages like [C](https://en.wikipedia.org/wiki/C_(programming_language)) work.  And I can think of absolutely no good reason to do so.  (`Mathematica<<Quaternions`, I'm looking at you!)  But it is trivial to automatically convert an array input to this function.

**Comment by calocedrus** [comment]
>> though as_quat_array isn't a math function, is there a reason for requiring exclusively floats?
How about accepting int as well?

> Keeping the array as integers would require creating all new quaternion_int datatypes

Though my title may have suggested otherwise, I didn't mean to have a quaternion_int dtype, what I was actually suggesting is expressed in your commit "cast to float when converting ...". 

> Mathematica<<Quaternions, I'm looking at you!

I'm not sure what you mean here, I'm not using Mathematica and never have.

**Comment by calocedrus** [comment]
PS: I salute your prompt replies and dedication to your quaternion module.
