### ISSUE TITLE
Dividing quaternions

### ISSUE THREAD

**Issue by noncom** [moble/quaternion#53]
As it is known, division on quaternions can go in two ways, for example, here's an abstract from Wikipedia:
> ... it is possible to divide two quaternions `p` and `q` in two different ways (when `q` is non-zero). That is, their quotient can be either `p q−1` or `q−1p`. The notation `p/q`  is ambiguous because it does not specify whether `q` divides on the left or the right.

These ways give different answers, which is important for calculations. So, with this package, how do I do either left or right division in particular? I could not find a hint on that, both playing with the library or within the test suite. Could you please give a little example?

**Comment by moble** [comment]
You've copied the wikipedia entry incorrectly, in one very important way.  The notation
<img width="21" alt="p_over_q" src="https://user-images.githubusercontent.com/1470769/27764111-62450ff2-5e5f-11e7-98f9-8a1f42be0e9d.png">
is indeed ambiguous, as wikipedia says; on the other hand the notation `p/q` is *not* ambiguous; that is clearly equivalent to `p * q^{-1}`.  This is pretty standard notation in non-commutative groups.

However, if you are unhappy with this or have trouble remembering it, you are welcome to just use explicit multiplication:
```python
p * q.inverse()
```
or
```python
q.inverse() * p
```

**Comment by noncom** [comment]
Thanks, this gives me an idea on how to do this operation. However, it remains unclear to me what rationale lies behind the fact that the code `p/q`  is analogous to only one of the possible divisions, `p * q^{-1}`, and why the other one is not presented as clear. Possibly there is a reason for that, but I am not well-accustomed to the underlying theory and computational math, I it could be I am missing something rather simple and well-known. Is this one of the possible divisions considered to be somehow superior over the other one? (can't find any mention on this in papers)

**Comment by moble** [comment]
I'm not saying that one is superior; they're different quantities that you need in different situations.  You have to decide which one you need for any given application.

All I'm saying is that `p/q` is defined as `p * q.inverse()`.  The reason is that this particular notation makes clear typographically that `p` is on the left and `q` is on the right, leading to a standard order of operations in which the corresponding multiplication (involving the inverse) is in the same order.  [Here is a wikipedia reference](https://en.wikipedia.org/wiki/Division_(mathematics)#Left_and_right_division) supporting my claim; [here is Mathematica's](http://reference.wolfram.com/language/ref/Divide.html.en); I'm sure I could find others in the mathematical literature.

On the other hand, the "p over q" notation is left-right symmetric, so there's no clear choice as to which one should come first in the multiplication.  And since either choice *could* be the correct one for some application, we just don't use that notation for non-commutative division.  (Plus, python code is one-dimensional, so we don't really have that option.)

**Comment by noncom** [comment]
This information is much appreciated! It brings clarity and explanation.
