### ISSUE TITLE
Can't install via pex

### ISSUE THREAD

**Issue by oliverdain** [moble/quaternion#56]
I wanted to create a single executable for a script I have that is using numpy-quaternion but pex can't find the right package:

```
$ pex numpy numpy-quaternion
Could not satisfy all requirements for numpy-quaternion:
    numpy-quaternion
```

It seems a bit odd since pip can install it fine.

**Comment by moble** [comment]
I don't know anything about `pex`, so unless you can point to something that my code is doing wrong, I'm going to have to assume that this is `pex`'s problem.  I only support `conda` and (barely) `pip`.  Unfortunately, I don't have the time to figure out problems with other workflows, but pull requests are welcome if you can find something that this package could do better.  Also note issue #55, which pointed out that `numpy` has to already be available before the setup can succeed for `quaternion`.

**Comment by oliverdain** [comment]
Understandable. I don't know much about pex myself but, in theory, it should work with anything that pip does. I suspect that there's a slight change in your setup.py or something that would fix things but since neither of us know what that might be I'll close the ticket.

thanks.

**Comment by moble** [comment]
Sorry.  The only thing I can think of is that I do require the latest version of `numpy`, because there are some important fixes in the latest releases that directly affect the behavior of `quaternions`. (Most importantly, issue #1 was fixed by `numpy` 1.13, so `conjugate` finally behaves correctly.)  So I list `numpy>1.13` in the [`requirements.txt` file](https://github.com/moble/quaternion/blob/master/requirements.txt#L1).  Maybe your `pex` can't find that version.  Otherwise, it looks like an insufficiently informative error.

**Comment by oliverdain** [comment]
I've played with `pex` enough that I think that error means it actually can't find `numpy-quaternion`. If it was having trouble finding numpy itself (or any other dependency) it'd list that as the dependency it can't satisfy. IIRC you're not using standard pyPi to distribute but are instead using some other repo, right? I think `pex` may be limited to pyPi.

**Comment by moble** [comment]
> IIRC you're not using standard pyPi to distribute but are instead using some other repo, right?

I think it's the standard one: https://pypi.python.org/pypi/numpy-quaternion

**Comment by oliverdain** [comment]
I'm stumped. I may look into this some more if packaging becomes a more important issue. Closing for now.
