### ISSUE TITLE
Using quaternion on raspberry

### ISSUE THREAD

**Issue by arturoribes** [moble/quaternion#60]
I am trying to use this library on a raspberry pi 3 with raspbian stretch and when trying to import quaternion I get the following error:

LLVM ERROR: Program used external function '__aeabi_unwind_cpp_pr0' which could not be resolved!

**Comment by moble** [comment]
My RPi is down at the moment, so I can't help directly.  But this looks like a compilation issue.  In particular, [google shows me](https://lists.linaro.org/pipermail/linaro-toolchain/2011-April/001101.html) that "__aeabi_unwind_cpp_pr0 is part of the standard ARM exception
handling code".  So something must be linking to something ARM-specific on your end.  Since this is so specific to your setup, I don't think I'll be able to help much.  But maybe if you gave me some details I could point you in the right direction.

How did you compile this package?  And what about other elements?  Are you using python from the OS, did you compile it, install it with conda, ...?

**Comment by arturoribes** [comment]
I will make a clean install on raspberry and try again, as I think I started getting this error after installing a version (early version, as LLVM on raspbian is 3.8) of numba.
I didn't compile this package, I installed using pip.

**Comment by moble** [comment]
First of all, unless you are using some of the more advanced functions (particularly, `frame_from_angular_velocity_integrand`), then you don't actually need `numba`; you can safely ignore the warnings.

Second, the ARM platform of raspberry pi doesn't have great support in the python community, so you'll need to use pretty old versions of things.  But it is possible to get it working.  I just did a totally fresh installation of raspbian, and used the system `pip` to install numpy and then `numpy-quaternion`.  It worked without problems.

I also used anaconda to install numpy, then pip to install this package within the conda installation.  It worked without problems.  The versions are all pretty old, but I guess you can't expect too much for a less-common platform.
