### ISSUE TITLE
Compiling code using numba with quaternion signature type

### ISSUE THREAD

**Issue by mszczuj** [moble/quaternion#62]
how to compile function using numba with quaternion type in signature?

`@numba.jit((numba.float64,numba.float64, ?????), nopython=True, nogil=True)`
`def B_t(x, y, z, rotated_over_q):`
`     pass`

**Comment by moble** [comment]
Unfortunately, numba does not support this kind of feature currently.  I looked into it a while ago, and the numba maintainers were not interested in adding that much flexibility.  In principle, you could probably use `cffi` to directly call into the C functions defined by this library, but I really don't know much about that.

But first, I wonder if you really need to jit this function.  The `quaternion` package already does a lot of operations very quickly, so unless your `B_t` function is doing something fancy, it might already be compiled as C code.  For example, there's `quaternion.rotate_vectors`, which is the most efficient way to rotate more than a few vectors.

Otherwise, the only way I can think of using quaternions with `numba` is to just pass each element of the quaternion to the function, like so:
```python
@numba.jit((numba.float64, numba.float64, numba.float64, numba.float64, numba.float64, numba.float64, ), nopython=True, nogil=True)
def B_t(x, y, z, q_w, q_x, q_y, q_z):
    pass

result = B_t(x, y, z, q.w, q.x, q.y, q.z)
```
You won't be able to use any of the quaternion's special features like multiplication inside the function, but at least you'll have access to its elements.

Feel free to ask for more details, but I'm closing this as unsolvable on my end.  (The solution has to come from numba's developers changing their code.)

**Comment by mszczuj** [comment]
Thanks for reply -- there is a need of jit over there. I could slice out some function for quaternion operation and put it over there but this somehow misses the whole point of using a quat library. 

Nevertheless great work with library
