### ISSUE TITLE
Error "No cast function available"

### ISSUE THREAD

**Issue by eelregit** [moble/quaternion#66]
I got the cast error if the quaternion array is contructed from the spherical coordinates:
```python
theta = np.random.rand(3) * np.pi
phi = np.random.rand(3) * 2 * np.pi
from_spherical_coords = np.frompyfunc(quaternion.from_spherical_coords, 2, 1)
q = from_spherical_coords(theta, phi)
quaternion.as_float_array(q)
```
with the following stack trace:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-c7e892e7b8aa> in <module>()
      5 from_spherical_coords = np.frompyfunc(quaternion.from_spherical_coords, 2, 1)
      6 q = from_spherical_coords(theta, phi)
----> 7 quaternion.as_float_array(q)

~/.conda/envs/rot/lib/python3.6/site-packages/quaternion/__init__.py in as_float_array(a)
     57 
     58     """
---> 59     return np.asarray(a, dtype=np.quaternion).view((np.double, 4))
     60 
     61 

~/.conda/envs/rot/lib/python3.6/site-packages/numpy/core/numeric.py in asarray(a, dtype, order)
    490 
    491     """
--> 492     return array(a, dtype, copy=False, order=order)
    493 
    494 

ValueError: No cast function available.
```
I also encountered the same error when calling spherical_functions.SWSH and WignerD functions.
But somehow the following lines work fine for me
```python
f = np.random.rand(12)
q = quaternion.as_quat_array(f)
quaternion.as_float_array(q)
```
The conda environment I used was in [conda_list.txt](https://github.com/moble/quaternion/files/1765515/conda_list.txt).

BTW, shouldn't the name "as_quat_array" actually be "from_float_array"?
And could you please also vectorize the from_spherical_coords method or make it a ufunc?
Thanks!!

**Comment by moble** [comment]
The problem is your use of `np.frompyfunc`, which returns an array with `dtype=object`.  And as the exception says, there is indeed no cast function to take `object` to `quaternion` — nor will there be, because `object`s are too general to know how to cast.  Of course, as you've pointed out, if `from_spherical_coords` were already a ufunc, you wouldn't have this problem...

> BTW, shouldn't the name "as_quat_array" actually be "from_float_array"?

Could be.  There was a logic to the naming system once, but it's pretty muddied now.  *Changing* it would break backwards compatibility, but I can certainly define `quaternion. from_float_array 
 = quaternion.as_quat_array`.  I'll do that in the next release.

> And could you please also vectorize the from_spherical_coords method or make it a ufunc?

This is the second time I've gotten this request this week, so I'll get on it ASAP.
