### ISSUE TITLE
Conventions used for quaternions and Euler angles

### ISSUE THREAD

**Issue by vikigenius** [moble/quaternion#67]
Can you please clarify the convention used for Quaternions and Euler angles?

Are you using the classic Euler angles or Tait–Bryan angles?
And as for Quaternions, are you using the JPL convention (Left handed, i.e i*j = -k) or the classic Hamiltonian convention (Right handed, i.e i*j = k)? Maybe you can add this to the README page?

I know how how you feel about Euler Angles and most of us feel the same way but sometimes the sensor input we get constrain us and we have to use it as a starting point.

**Comment by moble** [comment]
I steadfastly refuse to describe any conventions related to rotations in terms of names like "classic Euler" or "Tait-Bryan" because I have literally never seen a complete description of any such term — which has led me to find directly contradictory definitions for most such terms.  For example, people go as far as defining the rotation operators, but not how those operators are applied, and then different people inexplicably have different interpretations of how they should be applied.  I've also seen at least three distinct and contradictory definitions of the phrase "active vs. passive".

Instead, I think the only useful description is the one I give on [the page linked from that footnote](http://moble.github.io/spherical_functions/#euler-angles) where I complain about Euler angles.  More specifically, you can test for yourself that in this code
```python
quaternion.from_euler_angles(alpha, beta, gamma)
```
is the same as
```python
(alpha*quaternion.z/2).exp()*(beta*quaternion.y/2).exp()*(gamma*quaternion.z/2).exp()
```
Of course, even with that definition, I've seen people define that quantity as `R` and people define that as `R` inverse — and then in each of those two camps, I've seen people define a rotated vector to be `R*v*R^-1` and people define it to be `R^-1 * v * R`.  This package doesn't restrict you to one choice or the other in either case.  You have to figure out what conventions you want to use.

Similarly, you can see that
```python
quaternion(0, 1, 0, 0) * quaternion(0, 0, 1, 0)
```
is the same as
```python
quaternion(0, 0, 0, 1)
```
So `i*j = k` would be more like this package's conventions — depending on how you interpret lots of other things.

My advice is to test write unit tests for whatever code you're writing to ensure that known inputs give you the results you expect at each step of the process.  Having written much code myself, I can tell you that's the only thing that works.  Never rely on anyone else's tidy little names for their conventions.

**Comment by moble** [comment]
That Euler convention I cited above is also given explicitly in the docstring for `quaternion.from_euler_angles`.
