### ISSUE TITLE
Intel conda install requires pip numpy

### ISSUE THREAD

**Issue by nedlrichards** [moble/quaternion#70]
Installed python3.6 on miniconda with intel channel added

`conda config --add channels intel`

The latest [intel] numpy is 1.13.3

After installing quaternions following directions, importing the package leads to the error:

`RuntimeError: module compiled against API version ...`

This can be fixed by installing (and upgrading) numpy with pip, which installs numpy 1.14.1

**Comment by moble** [comment]
This sounds more like a bug for the maintainers of the intel conda channel.  Numpy 1.14 has been out for two months.  They should update, or you should expect to install an older version of this package.  I can't really be supporting older versions of numpy — especially when the only time I've heard of this problem is the niche usage as preferring intel packages even though anaconda's defaults use mkl.
