### ISSUE TITLE
numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by HTLife** [moble/quaternion#72]
```python
import numpy as np
import quaternion
np.quaternion(1,0,0,0)
```

```
RuntimeErrorTraceback (most recent call last)
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb


ImportErrorTraceback (most recent call last)
<ipython-input-6-9f69562c49db> in <module>()
      1 import numpy as np
----> 2 import quaternion
      3 np.quaternion(1,0,0,0)

/usr/local/lib/python2.7/dist-packages/quaternion/__init__.py in <module>()
      6 import numpy as np
      7 
----> 8 from .numpy_quaternion import (quaternion, _eps,
      9                                from_spherical_coords, from_euler_angles,
     10                                rotor_intrinsic_distance, rotor_chordal_distance,

ImportError: numpy.core.multiarray failed to import
```

**Comment by HTLife** [comment]
After reinstall numpy and numpy-quaternion, this issue could be resolve.
```
pip uninstall numpy
pip uninstall numpy-quaternion
pip install numpy numpy-quaternion
```

**Comment by moble** [comment]
For anyone else who finds this issue, the failed `multiarray` import is common across many modules that use numpy (not just this one), and is generally due to mismatched versions of libraries used to compile things — usually specifically numpy, not the module that depends on it.  So the usual solution to this problem is simply

    pip install --upgrade numpy

Some people on Windows have apparently also reported needing to restart their computers.

**Comment by bram-ivs** [comment]
If you don't want to (or unable) upgrade numpy, you can also compile numpy-quaternion from source to avoid the binary mismatch.

`pip install --no-binary ":all:" numpy-quaternion`
