### ISSUE TITLE
put quaternion on conda forge?

### ISSUE THREAD

**Issue by arsenovic** [moble/quaternion#74]
@moble, have you considered using the conda forge build system? i use it for scikit-rf, and thought it might be useful since you state in your docs that you  dont have a windows machine .

**Comment by moble** [comment]
I hadn't looked at conda-forge in a really long time.  I think I went with my own Travis/Appveyor solution because conda-forge wasn't yet good enough.  But now I've gotten really tired of both Travis and Appveyor, and it looks like conda-forge has solved the problems I have with them, so I'm [giving it another try.](https://github.com/conda-forge/staged-recipes/pull/5661)  Thanks for pointing this out.

**Comment by moble** [comment]
Ha!  And I just googled "conda forge upload to pypi" because apparently I had [exactly the same thought as you](https://github.com/conda-forge/conda-smithy/issues/705).

Currently I have [a solution](https://github.com/moble/quaternion/tree/master/deploy) to build all the wheels (using docker for the linux versions) and upload them.  But this takes quite a while, which means that I occasionally forget to update pypi.

**Comment by arsenovic** [comment]
glad to hear. pypi/conda need to integrate better

**Comment by moble** [comment]
It's now available [via conda-forge](https://anaconda.org/conda-forge/quaternion).  Thanks for the pointer!

**Comment by arsenovic** [comment]
sweet!
