### ISSUE TITLE
The result of quaternion.from_euler_angles() is the same for alpha and gamma

### ISSUE THREAD

**Issue by DanielKorz** [moble/quaternion#83]
When I use from_euler_angle(alpha, beta, gamma) function to compute the quaternions I came across the odd result:
```python
>>> quaternion.from_euler_angles(0,1,0)
quaternion(0.877582561890373, 0, 0.479425538604203, 0)
>>> quaternion.from_euler_angles(1,0,0)
quaternion(0.877582561890373, 0, 0, 0.479425538604203)
>>> quaternion.from_euler_angles(0,0,1)
quaternion(0.877582561890373, 0, 0, 0.479425538604203)
```
Surely, the quaternion for alpha !=0 should not be the same as for the matching value of gamma.

**Comment by moble** [comment]
[I don't usually answer questions like this](https://github.com/moble/quaternion/wiki/Euler-angles-are-horrible#opening-issues-and-pull-requests), but I can see that you're new to this sort of thing, so I'll respond just this once.

Before you open an issue (or a pull request) — or bother asking any question in any forum about any piece of code — you should at least glance at the documentation.  In python, the very least you can do is run the `help` command for whatever function you're looking at.  In this case, that would be `help(quaternion.from_euler_angles)`.  Run that right in python and you'll see that [the docstring](https://github.com/moble/quaternion/blob/2f4b3d3fe5a3a37cd900f63659c8ad17e0561526/__init__.py#L407-L436) tells you what conventions for Euler angles are being used by this function.  It also tells you specifically to read this page

    https://github.com/moble/quaternion/wiki/Euler-angles-are-horrible#opening-issues-and-pull-requests

before opening an issue.  If you read that page, you should understand that `from_euler_angles(0,0,1)` and `from_euler_angles(1,0,0)` really do represent the same rotation because one is a rotation about the `z` axis through 1 radian *followed* by two rotations through 0 radians, and the other is a rotation about the `z` axis through 1 radian *preceded* by two rotations through 0 radians.
