### ISSUE TITLE
Axis-angle conversions

### ISSUE THREAD

**Issue by SicariusNoctis** [moble/quaternion#86]
By Euler's rotation theorem, any rotation may be represented by a single axis and angle. Could this library implement support for two common operations:

```python
q = np.quaternion(...)

axis, angle = q.to_axis_angle()
q2 = quaternion.from_axis_angle(axis, angle)

assert q == q2  # True
```

Use cases:

 - Implemented by standard graphics libraries. (e.g. OpenGL)
 - Yet another common representation of rotations, but not evil like the dreaded Euler angles.
 - Such a representation makes it easy to [extrapolate the geodesic between two points](http://answers.unity.com/answers/168816/view.html) on a sphere. (I've also heard of other candidates like the exponential map, though I'm unsure whether it is accurate, free of abnormal behavior, and performant.)

```python
# using axis angle
def spherical_extrapolate(q1, q2, t):
    rot = q2 * q1.inverse()
    axis, angle = rot.to_axis_angle()
    return quaternion.from_axis_angle(axis, angle * t)

# using exponential map
def spherical_extrapolate(q1, q2, t):
    rot = q2 * q1.inverse()
    return rot**t * q1
```

**Comment by moble** [comment]
There are already very closely related functions named [`as_rotation_vector`](https://github.com/moble/quaternion/blob/168afa9d91fe64876b7f258f9a9e7a9f09cb8aa6/__init__.py#L328-L347) and [`from_rotation_vector`](https://github.com/moble/quaternion/blob/168afa9d91fe64876b7f258f9a9e7a9f09cb8aa6/__init__.py#L350-L370).  The main difference between the rotation vector and and axis-angle is that the rotation vector is simply the angle *times* a unit vector representing the axis.  Frequently, the rotation vector comes already in this form, so asking for the axis and angle separately is a waste of time.  A function returning the axis and the angle requires taking the norm — which only involves a few multiplications, a couple additions, and an expensive `sqrt` call — but is unnecessary in most cases that I know of and can easily be done by the user if desired.  It's very slightly more efficient to create a quaternion from axis and angle separately *if you already have them separately*, but overall converting to and from axis-angle is less efficient if you're going both ways.  I'm debating whether or not to add these functions.  Anyway, for now, just use the existing functions.

As for your use case of "spherical extrapolation", that's also already implemented under its usual name of [`slerp`](https://github.com/moble/quaternion/blob/168afa9d91fe64876b7f258f9a9e7a9f09cb8aa6/quaternion_time_series.py#L11-L35), which stands for "spherical linear interpolation".  (Of course, extrapolation is just interpolation to a point outside the input times, and works fine.)  It might also interest you to know that the next generalization [`squad`](https://github.com/moble/quaternion/blob/13ebe0d58339890793ac236305c68164596f4fa6/quaternion_time_series.py#L38-L154) (which is basically cubic rather than linear) is also implemented.

You are correct in thinking that there's a connection to the logarithm: the rotation vector is precisely 2 times the logarithm of a unit quaternion.  Similarly, you go from a rotation vector to the corresponding quaternion using the exponential function.  The quaternion logarithm is just like the complex logarithm, but more complicated.  For example, there are branch cuts, but they're multi-dimensional surfaces.  So I don't know if you would call them "free of abnormal behavior".  But ultimately, the axis-angle representation and rotation vectors rely on them, so there's no getting around it.  In fact, your `rot**t` term is the quaternion exponent, which is simply the exponential of `t` times the logarithm of `rot` — that is, `np.exp(t*np.log(rot))`.  So mathematically, your two versions of the functions are identical; in terms of code, they're basically wrappers around the same code.

On a related note, it may interest you to look at [the core code](https://github.com/moble/quaternion/blob/168afa9d91fe64876b7f258f9a9e7a9f09cb8aa6/quaternion.h#L466-L472) implementing `slerp`.  It checks to see if the two quaternions are close to each other or more nearly opposite.  Of course, since opposite quaternions represent the same rotation, unless you know what you're doing you should probably just flip the sign of one if they're nearly opposite, or you'll get crazy results.

**Comment by SicariusNoctis** [comment]
Thanks for the comprehensive reply.

Since you pointed out `as_rotation_vector` and `from_rotation_vector`, I would say that the "axis-angle" API is a little redundant.
