### ISSUE TITLE
implement square, real

### ISSUE THREAD

**Issue by paolini** [moble/quaternion#87]
I haven't found a way to compute the squared norm of a quaternion array. I can use `np.square(np.norm(q))` but this sound inefficient to me. If the function exists I would like to see an example usage in the documentation. Also I would like to take the real part of a quaternion: so that I could be able to write `sqr_q = (q * q.conj).real` but `.real` gives the whole quaternion back. Similarly it could be useful if `.imag` gives the imaginary parts (as a 3D vector).

Suggested behaviour:  np.square, np.real, np.imag to be extended to act on quaternions

**Comment by paolini** [comment]
Sorry, I now realize that `np.norm` is actually the squared norm of the quaternion and that `np.abs` is the norm. I suggest to add `np.square` as an alias for `np.norm` (which I find a confusing name) and definitely I would suggest to add examples in the main page documentation.

**Comment by moble** [comment]
I certainly don't mind adding more examples to the README, but I definitely will not add a `square` function because it's very easy to compute the square of a quaternion `q` as `q*q`.  Of course, you seem to misunderstand what "square" means: in every group — no matter how abstract — the square of an element is just that element times itself, which is not the same as the element times its conjugate (for groups in which a conjugate even exists), which is what `norm` computes.

As for `real` and `imag`, these functions are already implemented as you had hoped for individual quaternion objects.  Unfortunately, due to limitations of numpy, it appears that those can't be made to work for quaternion arrays without breaking them for other things — notably complex arrays.  I am keeping an eye on this problem.  For now, for the fastest way to get the respective parts, I recommend code like this:
```python
q_real = quaternion.as_float_array(q)[:, 0]
q_imag = quaternion.as_float_array(q)[:, 1:]
```

**Comment by paolini** [comment]
Thanks for your answer and for your work!

Just for the sake of discussion: in my experience I expect the function sqr to return the squared norm instead of the product of an element by itself. A library of vectors, matrices, complex numbers or quaternions for sure needs to implement such a function (the square of the norm). I would call it sqr because the sqr function on real numbers also is equal to the square of the norm, so we obtain a homogeneous interpretation and nice polymorphism. In some situations the same algorithm on different fields can be written in the exact same way if we intepret the sqr function like that.

Of course one could expect sqr(q) to be q*q if we also have a group operation (which is not the case, for example, for 3D vectors). But usually when I'm computing q*q I'm working in a context where also q*q*q and q*q*q*q is needed, so I would not expect to have a function for the particular case n=2. If I use the function sqr(q) to compute q*q and I get a real number instead of a quaternion I would almost certainly get an exception and immediately understand what is happening. Instead if I use norm(q) and obtain the squared norm while expecting the norm, it is much more difficult to find the error.

Anyway: anyone is free to add its layer of user defined functions, so this discussion is not much relevant. If you just add a warning in the documentation I will be contented. Maybe a simple example such as:

```
>>> k = quaternion.quaternion(0,0,0,1)
>>> (2*k).norm()
4.0
```

**Comment by moble** [comment]
> A library of vectors, matrices, complex numbers or quaternions for sure needs to implement such a function (the square of the norm)

Just to be clear, `quaternion.norm` returns the "Cayley norm" (as noted in its docstring) which is the version *without* the square-root, whereas `quaternion.abs` returns the version *with* the square-root.  The latter is consistent with the python/numpy treatment of complex numbers, whereas I don't think an analog of `quaternion.norm` is present natively in python or numpy.  Unfortunately, it is true that "norm" means different things to different people, and I can see why there might be some confusion.  But this is a choice that has been made; it's too late to unmake it.  The best I can do is to document it.

> the sqr function on real numbers also is equal to the square of the norm, so we obtain a homogeneous interpretation and nice polymorphism.  In some situations the same algorithm on different fields can be written in the exact same way if we interpret the sqr function like that.

But we *already have* a homogeneous interpretation and nice polymorphism that applies to *every mathematical structure with a product that I've ever seen*: the "square" of an element is the product of an element with itself.  In fact, now that I look, I see that there is a function called `numpy.square` that operates on complex numbers just as I've said.  If you're looking for a way to create more confusion, introducing a new square or sqr function with a different interpretation would be a good way to do it — especially since the functionality you're looking for already exists, just under a different name than you want.

> one could expect sqr(q) to be q*q if we also have a group operation (which is not the case, for example, for 3D vectors).

3D vectors absolutely *do* have a group operation: it's called the [geometric product](https://en.wikipedia.org/wiki/Geometric_algebra#The_Geometric_Product) and it's actually the basis for the modern understanding of how quaternions work.  But more relevant to this case, 3D vectors *as mapped into quaternions* have a group operation — which is all that matters here.

**Comment by moble** [comment]
Following on with the `norm`/`abs` discussion above, it's worth pointing out that the conventions I'm using here are consistent with the [Boost implementation of quaternions](http://www.boost.org/doc/libs/1_66_0/libs/math/doc/html/math_toolkit/value_op.html#math_toolkit.value_op.abs), as well as [python's](https://docs.python.org/3.7/library/functions.html#abs), [numpy's](https://docs.scipy.org/doc/numpy/reference/generated/numpy.absolute.html), and [C++'s](http://www.cplusplus.com/reference/complex/norm/) standards for complex numbers.
