### ISSUE TITLE
Calling np.angle() on a numpy array of quaternions gives an error

### ISSUE THREAD

**Issue by nathanielvirgo** [moble/quaternion#91]
**Describe the bug**
calling np.angle() on a numpy array of quaternions gives the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ndv/Library/Python/3.7/lib/python/site-packages/numpy/lib/function_base.py", line 1352, in angle
    return arctan2(zimag, zreal) * fact
TypeError: ufunc 'arctan2' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**To Reproduce**

```python
import numpy as np
import quaternion as quat

np.angle(np.array(quat.quaternion(1,1,1,1)))
```
**Expected behavior**
I expected a numpy array of dtype float containing the angle of each quaternion, because something similar works with most (all?) of the other functions defined by this package. 

**Environment (please complete the following information):**
 - OS, including version
OS X El Capitan version 10.11.6, Python 3.7

 - Installation method (conda, pip, or compiled from source)
Python installed via macports, quaternion installed via pip

 - Numpy version (use `np.version.version`)
1.15.0

 - Quaternion version (use `quaternion.__version__`)
'2018.8.19.2.41.1'

**Comment by moble** [comment]
This problem is more of a numpy issue.  Basically, I don't want to override any numpy functions, so I can only make numpy functions work with quaternions if those functions look for attributes on the objects found in numpy arrays.  But as you can see [in the `np.angle` code itself](https://github.com/numpy/numpy/blob/6a58e25703cbecb6786faa09a04ae2ec8221348b/numpy/lib/function_base.py#L2130), the numpy authors have basically hard-coded an assumption that the input to that function will be either real or complex.  So there's not much I can do there.  Things like `np.exp(quaternion.quaternion(1,1,1,1))` work because the `np.exp` function looks for the `quaternion.exp` attribute.

However, there are relevant functions inside `quaternion` — most importantly [`quaternion.as_rotation_vector`](https://github.com/moble/quaternion/blob/8643c1118bec548ac92e3bd48fbec8df3e190c26/__init__.py#L329).  The norm of this result is the angle that I assume you're talking about.  (See also the discussion [here](https://github.com/moble/quaternion/issues/86#issuecomment-402613374).)  For example, you could do something like this:
```python
import numpy as np
import quaternion

rot_vec = quaternion.as_rotation_vector(np.array(quaternion.quaternion(1,1,1,1)))
angle = np.linalg.norm(rot_vec, axis=-1)
```
