### ISSUE TITLE
package install failure "fatal: Not a git repository"

### ISSUE THREAD

**Issue by belm0** [moble/quaternion#94]
package install fails, it appears to be a recent regression

```
$ pip uninstall numpy numpy-quaternion
$ pip install numpy-quaternion
$ pip install numpy-quaternion
Collecting numpy-quaternion
  Using cached https://files.pythonhosted.org/packages/16/13/a4d3571c533bce29dd9b4f2c88af70a0d32520af65d457fd388a1bf11fb2/numpy-quaternion-2018.9.30.23.2.27.tar.gz
    Complete output from command python setup.py egg_info:
    fatal: Not a git repository (or any of the parent directories): .git
    The variable 'package_version' was not present in the environment
    Setup.py using strftime version='2018.10.1.3.46.35'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ww/51xbs7nx6t16x7mh225q9x1h0000gn/T/pip-build-0y3qg4i_/numpy-quaternion/setup.py", line 51, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
```

**Comment by moble** [comment]
First of all, I don't understand why you've edited your comment.  As it currently stands, it makes no sense because it appears that you pip-install it once, there is no output or error, and then you install it again in precisely the same way and then get output and an error.  You can't expect people to reliably diagnose a problem without knowing what actually happened.  But in this case, I think it's clear enough.

You should always try to *understand* error messages, rather than stopping at the first thing that looks strange.  The message about git is only fatal to that subprocess; the setup recovers with no trouble.  In particular, that message comes before the beginning of the traceback, which should be a clear signal that it is not the source of the problem.  Now, if you read the traceback itself, you see that the problem comes from lines 51 of `setup.py`.  And if you look at [that line in the file](https://github.com/moble/quaternion/blob/6df185fef655affaf29002448954161ec30004a5/setup.py#L51), you'll see that it's just `import numpy`.  And the error itself says `No module named 'numpy'`.

So that's the problem: you haven't installed numpy.  If you look at the [README for this module](https://github.com/moble/quaternion#installation), you'll see that it says multiple times that the pip command to install it is `pip install numpy numpy-quaternion`.  Unfortunately, numpy is required for building the extension, and there is no way to force setuptools to install it when it is needed before trying to *build* the extension — only before *installing* it.

Now, the reason your experience has changed is presumably because pip installed a "wheel" before, which doesn't require building from source.  Unfortunately, too many things have broken recently in ptyhon's distribution methods, so I haven't yet been able to build the wheels for linux or macos (and one of the builds failed for windows).  I hope to get things working soon.  But in the mean time, just install numpy.
