### ISSUE TITLE
what quaternion convention is this package using?

### ISSUE THREAD

**Issue by Kai-46** [moble/quaternion#96]
Hi guys, 

I just learned that there are two conventions for conversion between a quaternion and a rotation matrix. Details can be found at [https://fzheng.me/2017/11/12/quaternion_conventions_en/](https://fzheng.me/2017/11/12/quaternion_conventions_en/). So I'm wondering what convention this package is adopting, Hamilton or JPL?

Thanks in advance.

**Comment by moble** [comment]
Like any reasonable person, I follow Hamilton's convention.  But in general, I don't think you should ever take anyone's word for it when they describe things like Hamilton/JPL/Shuster, or even names like active vs. passive, because I have found opposite interpretations for literally every term I have ever looked up dealing with rotations.  Instead, I recommend that you derive everything yourself following your own conventions, and do basic tests on any software packages to verify that they do what you expect.  In this case, you should do something like this:

```python
>>> quaternion(0, 1, 0, 0) * quaternion(0, 0, 1, 0)
quaternion(0, 0, 0, 1)
```

Personally, I interpret this to mean `x*y=z` (which many would style `i*j=k`), but even that is a different interpretation than some people.  I discussed this more in #67.

On a related note, your blog suggests you may be interested in understanding these issues more deeply.  Quaternions are just a poor reflection of the beautiful, simple, and unified language of [geometric algebra](https://en.wikipedia.org/wiki/Geometric_algebra).  It really is much easier than any other system, it explains most of the seeming contradictions in the old vector-vs-quaternion debate, and it generalizes immediately to solve more complicated problems.  I cannot recommend highly enough the book [Geometric Algebra for Physicists](https://www.amazon.com/Geometric-Algebra-Physicists-Chris-Doran/dp/0521715954).

**Comment by Kai-46** [comment]
Thanks so much for the detailed explanations. @moble
